### PR TITLE
LAST_RELEASED=3.20.0

### PR DESCRIPTION
**Pull request by elharo**
@acozzette We might want to add this to the release process since it seems this hasn't been updated for quite a while.

### CODE REVIEW

**Comment by elharo** [comment]
Possibly. The variable is used though for C# and PHP.

**Comment by elharo** [comment]
This fails though it's not immediately obvious how this change leads to this failure:

```
========================================================================
    Checking on the ObjC Runtime Code
========================================================================
objectivec/DevTools/full_mac_build.sh: objectivec/DevTools/pddm_tests.py: /usr/bin/python3: bad interpreter: No such file or directory
```

**Comment by fowles** [comment]
that is a pre-existing failure

**Comment by acozzette** [comment]
I think things get complicated when protobuf generated code is published to package managers like Maven Central and PyPI. If we required all generated code to have been generated by the same protoc version matching the runtime, then dependency management would become difficult because any packages containing protobuf generated code would all have to be upgraded in lockstep with the protobuf runtime. Also if we release a new runtime without a major version increment, then we're implicitly promising that it's safe to upgrade, so I think we do need to tolerate a certain degree of mismatch between protoc version and runtime version.

However, I'm not sure we should keep the compatibility tests, because if we're not actively updating them then they're not necessarily adding much value.

**Comment by fowles** [comment]
I am nearly certain that this workflow doesn't work for C++ and is unsupported for Java.

**Comment by elharo** [comment]
The tests are passing now, which is good. I'm still not sure whether we want to keep doing this or drop the compatibility tests.

**Comment by elharo** [comment]
So how do we want to move forward with this?

Option A: Update the variable and add this to the release process
Option B: Delete the variable and everything that depends on it

**Comment by fowles** [comment]
I lean towards B

**Comment by fowles** [comment]
if you want to merge this so it is at least unbroken first, we can do that

**Review by fowles — APPROVED** [review]

**Comment by elharo** [comment]
OK, I'll merge and then try a PR to reomve it completely and see what happens.

**Pull request merged**
