### PR TITLE
Modify port_def.inc to ignore -Wshadow warning

### LINKED ISSUE #13037: Rename shadowed variables
**What version of protobuf and what language are you using?**
Version: main
Language: C++

**What operating system (Linux, Windows, ...) and version?**
MacOS

**What runtime / compiler are you using (e.g., python version or gcc version)**
```cpp
# Compile failed
$ bazel build --copt='-Wshadow-all' :protoc :protobuf
$ clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**What did you expect to see**
Shadowed variables can cause readability issues. Ensure a shadowed
variable isn't used in header files which may be used in a dependent
project that explicitly disables them.
`bazel build --copt='-Wshadow-all' :protoc :protobuf` executed successfully.

### PR DESCRIPTION
**Pull request by 4kangjc**
Closes #13037

### CODE REVIEW

**Review by fowles — APPROVED** [review]

**Comment by fowles** [comment]
there was a thing in our tree that held up our automation.  Do you mind rebasing to latest?

**Review by fowles — APPROVED** [review]

**Comment by 4kangjc** [comment]
> there was a thing in our tree that held up our automation.  Do you mind rebasing to latest?

OK.

**Review by fowles — APPROVED** [review]

**Comment by 4kangjc** [comment]
@fowles Is there anything else that needs to be changed?

**Comment by fowles** [comment]
no, we need to kick a few things on our side

**Pull request closed without merging**
