### PR TITLE
Ported Ruby extension to upb_msg

### PR DESCRIPTION
**Pull request by haberman**
This PR implements a significant refactoring of the Ruby C extension. The internal representation of messages is changing from a custom Ruby-specific raw memory layout to using `upb_msg`, a representation that is defined in the upb library. Upb defines a [reflection interface](https://github.com/protocolbuffers/upb/blob/master/upb/reflection.h) that we can use to access message data from C.

This refactoring should lead to much better performance, particularly when parsing large messages. The old code would eagerly create a Ruby object for every single sub-message parsed from the wire, which meant tons of objects would participate in garbage collection. The new extension only creates C objects at parse time, and Ruby wrapper objects are created on demand, only when accessed.

This fixes a number of conformance errors in the old extension.

There are a few slight behavior changes:

1. The old code threw `Google::Protobuf::TypeError` in some cases but plain `TypeError` in others. The new code standardizes on using `Google::Protobuf::TypeError` everywhere.
2. The old JSON and `#inspect` serializers were emitting empty optional fields, whereas they should only be emitted when they are set.
3. We no longer prohibit maps for proto2 protos.
4. If you try to compile a proto2 proto containing extensions, we emit a warning an ignore it instead of rejecting the proto completely.

### CODE REVIEW

**Comment by qnighy** [comment]
@googlebot I consent.

**Comment by KapilSachdev** [comment]
Is it ready to be shipped?

xref: #7922

**Review by gerben-s — APPROVED** [review]

**Comment by haberman** [comment]
@KapilSachdev the change is looking great in unit tests. I'm hoping to get some feedback about whether it is working for users before I merge.

A team at Google is planning to try it out sometime this week, but any other feedback from open-source users would be very helpful too.

**Comment by ryanseys** [comment]
Oooh, I'm very interested in this. When do you anticipate this will land?

**Comment by brettfishman** [comment]
+1

**Comment by haberman** [comment]
This will be in the next release, which should land in the next few weeks.

**Comment by hatstand** [comment]
I suspect this is the cause of https://github.com/protocolbuffers/protobuf/issues/8311 but only due to the size of the changeset.

**Pull request merged**
