### PR TITLE
[Kotlin] remove redundant public modifiers for compiled code

### PR DESCRIPTION
**Pull request by j-min5u**
fixes: #9641 : removes all public visibility modifiers from kotlin protobuf code generation

### CODE REVIEW

**Comment by deannagarcia** [comment]
If you fix the conflicts I can try to run the tests again.

**Comment by j-min5u** [comment]
@deannagarcia done 😄

**Comment by deannagarcia** [comment]
If you have a chance to look at the failures that would be great, otherwise I can take a look when I have a chance (but will probably be a week before I get to it).

**Comment by j-min5u** [comment]
I made a fix where a `val` was accidentally removed along with a `public`. It should hopefully fix the failures

**Review by deannagarcia — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
