### PR TITLE
Java should presize fixed size primitives lists

### PR DESCRIPTION
**Pull request by faucct**

### CODE REVIEW

**Comment by zhangskz** [comment]
Failing checks show the following error:

```
bazel-out/k8-opt/bin/external/com_google_protobuf/java/core/_javac/core-no-manifest-do-not-use/libcore-no-manifest-do-not-use_tmp/com/google/protobuf/DescriptorProtos.java:2814: error: no suitable method found for mutableCopy(IntList,int)
          publicDependency_ = mutableCopy(publicDependency_, capacity);
                              ^
    method GeneratedMessageV3.mutableCopy(IntList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(LongList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(FloatList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(DoubleList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(BooleanList) is not applicable
      (actual and formal argument lists differ in length)
bazel-out/k8-opt/bin/external/com_google_protobuf/java/core/_javac/core-no-manifest-do-not-use/libcore-no-manifest-do-not-use_tmp/com/google/protobuf/DescriptorProtos.java:2901: error: no suitable method found for mutableCopy(IntList,int)
          weakDependency_ = mutableCopy(weakDependency_, capacity);
                            ^
    method GeneratedMessageV3.mutableCopy(IntList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(LongList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(FloatList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(DoubleList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(BooleanList) is not applicable
      (actual and formal argument lists differ in length)
bazel-out/k8-opt/bin/external/com_google_protobuf/java/core/_javac/core-no-manifest-do-not-use/libcore-no-manifest-do-not-use_tmp/com/google/protobuf/DescriptorProtos.java:36014: error: no suitable method found for mutableCopy(IntList,int)
            path_ = mutableCopy(path_, capacity);
                    ^
    method GeneratedMessageV3.mutableCopy(IntList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(LongList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(FloatList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(DoubleList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(BooleanList) is not applicable
      (actual and formal argument lists differ in length)
bazel-out/k8-opt/bin/external/com_google_protobuf/java/core/_javac/core-no-manifest-do-not-use/libcore-no-manifest-do-not-use_tmp/com/google/protobuf/DescriptorProtos.java:36101: error: no suitable method found for mutableCopy(IntList,int)
            span_ = mutableCopy(span_, capacity);
                    ^
    method GeneratedMessageV3.mutableCopy(IntList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(LongList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(FloatList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(DoubleList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(BooleanList) is not applicable
      (actual and formal argument lists differ in length)
bazel-out/k8-opt/bin/external/com_google_protobuf/java/core/_javac/core-no-manifest-do-not-use/libcore-no-manifest-do-not-use_tmp/com/google/protobuf/DescriptorProtos.java:38079: error: no suitable method found for mutableCopy(IntList,int)
            path_ = mutableCopy(path_, capacity);
                    ^
    method GeneratedMessageV3.mutableCopy(IntList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(LongList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(FloatList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(DoubleList) is not applicable
      (actual and formal argument lists differ in length)
    method GeneratedMessageV3.mutableCopy(BooleanList) is not applicable
      (actual and formal argument lists differ in length)
```

**Comment by faucct** [comment]
@zhangskz , @shaod2 , anyone?

**Comment by faucct** [comment]
It looks like the tests did not try to run.

**Comment by faucct** [comment]
Bump

**Comment by faucct** [comment]
Looks like Java tests are fine and only failures are unrelated C++ ones.

**Comment by faucct** [comment]
Though, I have realized now that the length is bytes, so I have to scale it to the type size. BRB with the changes.

**Comment by faucct** [comment]
Done and local tests are still green.

**Comment by faucct** [comment]
Bump

**Review by googleberg — APPROVED** [review]

**Comment by googleberg** [comment]
Looks like the C++ tests are failing. Maybe rebase and we try again?

**Comment by faucct** [comment]
rebased

**Review by googleberg — APPROVED** [review]

**Comment by faucct** [comment]
tests, please)

**Review by googleberg — APPROVED** [review]

**Comment by faucct** [comment]
let's merge?

**Comment by googleberg** [comment]
This change is failing on some internal tests. I'll need to sort through that.

**Comment by faucct** [comment]
When will you be able to do that? Maybe I could do something about that if the issue can be fixed in the public code.

**Comment by googleberg** [comment]
The change to support pre-allocating these repeated fields is in the 24.0 release.

**Pull request closed without merging**
