### PR TITLE
Removes unused code in core and related lint warnings

### PR DESCRIPTION
**Pull request by solodynamo**
Screenshot of one of the warnings while compiling.
screen shot 2019-02-25 at 12 10 11 pm

### CODE REVIEW

**Comment by solodynamo** [comment]
I signed it!

**Comment by solodynamo** [comment]
@TeBoring @acozzette any update on this? Also not sure why CI tests are failing after unused code removal.

**Comment by acozzette** [comment]
@solodynamo Sorry for taking so long to get back to you on this. It looks like someone else already removed the dead code from cpp_helpers.cc but that looks great to remove it from cpp_message_field.cc as well. If you want to rebase this and fix the conflicts then I'll merge it. I think the CI failures are an unrelated temporary issue.

**Comment by solodynamo** [comment]
@acozzette done

**Comment by acozzette** [comment]
Thanks @solodynamo!

**Pull request merged**
