### PR TITLE
Added tuple seconds and nanoseconds deconstruction

### PR DESCRIPTION
**Pull request by mwpowellhtx**
Pursuant to the [issue](https://github.com/protocolbuffers/protobuf/issues/8168).

Thank you.

### CODE REVIEW

**Comment by mwpowellhtx** [comment]
@googlebot I signed it!

**Comment by mwpowellhtx** [comment]
@Mizux I'm not sure what `Failing after 2s — 1/1 Fail(s): LABEL,` is... would you look into it please? Thank you...

**Comment by mwpowellhtx** [comment]
Meh, started with _VS Code_, no compiler verification. Opened `Google.Protobuf.sln` through Studio, and fixing a couple of minor syntactical issues.

**Comment by Mizux** [comment]
@mwpowellhtx please reword your commit to prepend text with "C#: "
It seems protobuf have a commit naming convention

note: While working for Google on OR-Tools (as a temp), I'm not part of the protobuf team ;)

**Comment by mwpowellhtx** [comment]
Simplified the implementation and pushed to my repo branch. Will update the PR.

**Comment by mwpowellhtx** [comment]
@Mizux Ah ok... In the comments?

**Comment by Mizux** [comment]
Then rebase and squash all your commits ;)

**Comment by mwpowellhtx** [comment]
@Mizux Re: branches, no problem. I tend to commit "micro" sometimes draft bits. The Git diffs are pretty sturdy I have found, but I can wrap it up tidier of course. ;)

**Comment by mwpowellhtx** [comment]
@Mizux So... did it merge? Or do I need to resubmit (apparently)?

**Comment by Mizux** [comment]
seems you need to create a new PR since you close this one ?

**Comment by mwpowellhtx** [comment]
@Mizux Didn't close it, but somehow Github PR is smart enough to detect a no-diff branch based PR, rightly so... I did open a new one BTW.

**Pull request closed without merging**
