### PR TITLE
Request SummaFT extension closes #7315

### LINKED ISSUE #7315: Request for custom extension for SummaFT
Hi,

I'd like to have custom extension allocated for SummaFT protoc-plugins to docs/options.md.

A number of 1080 seems vacant, but please allocate appropriate number for us.
The project website is private but will be public end of summer.  You can use www.summaft.com for now.

see https://github.com/protocolbuffers/protobuf/pull/7314

Thanks!

### PR DESCRIPTION
**Pull request by wibobm**
SummaFT develops a protoc plugin for both internal and external use that allows specific extensions to be made to extend the platform for GraphQL and OpenAPI 3.

### CODE REVIEW

**Comment by wibobm** [comment]
@googlebot I signed it!

**Comment by wibobm** [comment]
@googlebot I signed it!

**Comment by wibobm** [comment]
release notes: no

**Comment by acozzette** [comment]
@wibobm Sorry but I just merged another PR which conflicts with this--could you rebase and update to take the next available number, which I think is now 1085?

**Comment by wibobm** [comment]
> @wibobm Sorry but I just merged another PR which conflicts with this--could you rebase and update to take the next available number, which I think is now 1085?

@acozzette - all rebased

**Pull request merged**
