### PR TITLE
Fix newly appeared -Wunused-parameter

### PR DESCRIPTION
**Pull request by georgthegreat**
Please, consider cherry-picking this fix into 3.17 branch.

### CODE REVIEW

**Comment by acozzette** [comment]
@georgthegreat If you can rebase this onto the 3.17.x branch then I can merge it there directly.

**Comment by georgthegreat** [comment]
I had to create new PR over 3.17.x. You can find at #8587.

You can close this if you prefer merging from 3.17.x instead of this PR.

**Comment by acozzette** [comment]
Thanks, @georgthegreat. I merged the other PR so I will go ahead and close this one. The other fix will make it into master soon when I merge 3.17.x into master.

**Comment by georgthegreat** [comment]
Ok, thanks!

**Pull request closed without merging**
