### PR TITLE
Add isKnownType to php Google\Protobuf\Internal\AnyBase

### PR DESCRIPTION
**Pull request by solodkiy**
This is is a simple method to check is Any type could be unpacked or not without trigger exception.

### CODE REVIEW

**Comment by solodkiy** [comment]
@googlebot I signed it!

**Comment by TeBoring** [comment]
I think users of Any should make sure the descriptor is known. Providing `isKnown` seems to change this assumption, in which user can intentionally handle unknown types in runtime.

**Comment by solodkiy** [comment]
I see something like this as use case:
```
message QueueMessage {
  string from = 1;
  google.protobuf.Timestamp fired_at = 2;
  google.protobuf.Any message_data = 3;
}
```

You could send any message in this format through kafka, but some of consumers could not be update to latest version and don't know some of send messages.
So I assume some code like 
```
if (!$queueMessage->getMessageData()->isKnownType()) {
  // skip unknown message
}
```
could be helpful in this case.

**Comment by haberman** [comment]
Why not just attempt to unpack, and catch the exception if the type is unknown?

```php
try {
    $unpacked = $queueMessage->getMessageData()->unpack();
} catch (Exception $e) {
    // Unknown type, skip.
}
```

**Comment by haberman** [comment]
Why not just attempt to unpack, and catch the exception if the type is unknown?

```php
try {
    $unpacked = $queueMessage->getMessageData()->unpack();
} catch (Exception $e) {
    // Unknown type, skip.
}
```

**Comment by acozzette** [comment]
@solodkiy I'm going to close this since it's been a few weeks with no action, but feel free to comment here if you would like to reopen this.

**Pull request closed without merging**
