### PR TITLE
Cygwin: error: ‘constinit’ variable ‘google::protobuf::_Struct_default_instance_’ does not have a constant initializer #9562

### PR DESCRIPTION
**Pull request by chronoxor**
What version of protobuf and what language are you using?
Version: master
Language: C++
Windows Cygwin 3.3.4
GCC 11.2.0

### CODE REVIEW

**Comment by chronoxor** [comment]
@acozzette cla/google is signed please check if the PR is mergeable now?

**Review by acozzette — APPROVED** [review]

**Comment by acozzette** [comment]
@chronoxor Thanks!

**Comment by chronoxor** [comment]
@acozzette sure! Will check right now.

**Comment by chronoxor** [comment]
@acozzette the latest protobuf main works fine for me:
image

**Pull request merged**
