### PR TITLE
Fix binary compatibility in FieldCodec factory methods

### PR DESCRIPTION
**Pull request by ObsidianMinor**
Fix for #6379.

### CODE REVIEW

**Comment by jskeet** [comment]
I'm confused about why we have these defaultValue parameters at all - they never seem to be used. My guess is that that's a separate bug, that the existing methods aren't calling the right constructor. (That should be confirmed with a breaking test before being fixed, and that should probably be in a different PR.)

I would make the overloads delegate to the methods accepting a default value though, unless there's a good reason not to.

**Comment by ObsidianMinor** [comment]
> that should probably be in a different PR

Right. I was going to do it in this one but decided to fix it in #5936 when the different default values would be put to use (with extensions being finalized then).

**Comment by TeBoring** [comment]
Why previously there were no test to catch it?

**Comment by ObsidianMinor** [comment]
There was no code to test against. There was no way to generate extension identifiers at the time (before #5936) so rather than add tests for code that couldn't actually be used (unless the consumer decided to implement the interfaces and use the API manually) I decided to wait until the last PR. Then the code could be fully tested properly when unittest.proto could actually be generated in the test project.

**Comment by jtattermusch** [comment]
Fine to merge (and backport to v3.9.x branch)?

**Pull request merged**
