### PR TITLE
Fix parsing negative Int32Value that crosses segment boundary

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/protocolbuffers/protobuf/issues/8027

### CODE REVIEW

**Comment by JamesNK** [comment]
@jtattermusch

**Comment by jtattermusch** [comment]
Looks like the bug was originally introduced already in https://github.com/protocolbuffers/protobuf/pull/6843/files#diff-d740c4c5c32b30dbd921e0d61adac31089322bceaa2aa34b6b3020951817779eR851 (and it stayed around when moving the code to `ParsingPrimitivesWrappers.cs`)

@chrisdunelm  since you are the author of #6843, can you please review?

**Comment by jtattermusch** [comment]
@acozzette  I believe this is a release blocker - feel free to also review.

**Review by chrisdunelm — APPROVED** [review]
LGTM

**Review by jtattermusch — APPROVED** [review]
LGTM, thanks for the quick fix.

**Pull request merged**
