### PR TITLE
Don't break the trace

### PR DESCRIPTION
**Pull request by umpirsky**

### CODE REVIEW

**Comment by haberman** [comment]
It looks like the CLA check failed, we will need you to be covered under the CLA before we can accept this change: https://cla.developers.google.com/

**Comment by umpirsky** [comment]
Screenshot from 2022-12-16 08-51-41

**Comment by haberman** [comment]
Sorry for the delay!

The CLA check is fixed. Would you be able to rebase on the main branch? You've caught us in the middle of a migration to GItHub Actions.

**Comment by haberman** [comment]
[@dependabot](https://github.com/dependabot) rebase

**Pull request closed without merging**
