### PR TITLE
[bazel] Be able to specify protobuf plugins in py_proto_library

### PR DESCRIPTION
**Pull request by moshe**
This PR adds the ability to specify custom proto plugins for the `py_proto_library` rule
I wanted to use https://github.com/dropbox/mypy-protobuf but it seems like it not possible with the current rule.
I made the PR backward compatible, let me know what to do think🙂

### CODE REVIEW

**Comment by moshe** [comment]
@googlebot I signed it!

**Comment by moshe** [comment]
ping?

**Comment by moshe** [comment]
cc @Yannic

**Comment by moshe** [comment]
You are right, I will fix it and better test it. Fix will be submitted in the next days.
Thanks @Yannic

**Comment by acozzette** [comment]
I'm going to close this PR since there's been no activity in a few months. We actually have some work underway to have protoc generate pyi files, so that might address the motivation for this PR anyway.

**Comment by micahjsmith** [comment]
@acozzette to close the loop on this thread - I believe protoc now generates pyi files using `--pyi_out`, but `py_proto_library` macro does not support that and it seems protobuf repo is no longer responsible for that macro (https://github.com/protocolbuffers/protobuf/issues/10366) - can anyone point to a way forward for people who want to use bazel + protoc + pyi_out?

**Comment by acozzette** [comment]
We are going to keep our `py_proto_library` macro around until Bazel releases their own version, so I think we would OK accepting a pull request that adds support for `--pyi_out`, as long as it's compatible with the future Bazel version.

**Pull request closed without merging**
