### PR TITLE
[C#] - Allow Retrieval of Nested Metadata

### PR DESCRIPTION
**Pull request by abbotware**
remove check to allow retrieval of nested enum metadata

fix for issue:
https://github.com/protocolbuffers/protobuf/issues/10696

### CODE REVIEW

**Comment by abbotware** [comment]
FYI - All C# unit tests pass with this change

**Comment by jskeet** [comment]
I'm going to have a look at the issue when I get the chance, later in the week. I'll be adding various tests, aside from anything else - but I really need to take some time over it to make sure I don't break anything.

I suggest you close this PR, as I'll create my own when I get the chance.

**Comment by abbotware** [comment]
@jskeet - would creating additional method work as an alternative?  (see new commit) From what I can see, the only places this method is reference are unittests.  An additional method then won't break functionality for any library users

I just want access to the data that's already in there :-)   but alas, all the objects are sealed internal  :-/

**Comment by jskeet** [comment]
That would certainly make sure it's not breaking, but changing the existing behaviour may be a better option if it brings it into line with other languages. Again, please be patient until I have time to look at this properly. (Bear in mind that it won't be released until the next release comes anyway.)

**Comment by abbotware** [comment]
well, no rush - I can get access to the internal DescriptorPool via some dirty reflection tricks :-P 

just willing to help :-)

**Comment by jskeet** [comment]
Closing this as the related issue is closed.

**Pull request closed without merging**
