### PR TITLE
Update third_party.md

### PR DESCRIPTION
**Pull request by yksten**
C++struct and protobuf conversion library, which also supports generating header files according to proto.

### CODE REVIEW

**Comment by googleberg** [comment]
@yksten please sign the CLA so that we can assign a reviewer. Instructions [here](https://github.com/protocolbuffers/protobuf/pull/11039/checks?check_run_id=9630507103)

**Comment by yksten** [comment]
> C++struct and protobuf conversion library, which also supports generating header files according to proto.

**Comment by yksten** [comment]
> done

**Comment by yksten** [comment]
> @yksten please sign the CLA so that we can assign a reviewer. Instructions [here](https://github.com/protocolbuffers/protobuf/pull/11039/checks?check_run_id=9630507103)

done

**Comment by yksten** [comment]
> @googleberg 
done

**Comment by yksten** [comment]
@google-cla[bot] 
done

**Review by esorot — APPROVED** [review]

**Pull request merged**
