### PR TITLE
Add -Werror for CI builds

### PR DESCRIPTION
**Pull request by keith**
Fixes https://github.com/protocolbuffers/protobuf/issues/6015

### CODE REVIEW

**Comment by keith** [comment]
This will fail on CI until https://github.com/protocolbuffers/protobuf/pull/6011 and https://github.com/protocolbuffers/protobuf/pull/6014 are fixed

**Comment by acozzette** [comment]
I kicked off the CI builds just now so we should see a failure in the Bazel tests.

**Comment by keith** [comment]
I've updated this to not add `-Werror` for examples because there are a lot of warnings in there that we don't control

**Comment by keith** [comment]
This also now depends on https://github.com/protocolbuffers/protobuf/pull/6025

**Comment by keith** [comment]
@acozzette I _think_ this should be green now

**Pull request merged**
