### PR TITLE
Add micro Registered Extension Number

### PR DESCRIPTION
**Pull request by vtolstov**
unistack-org/micro (microservices framework) uses protoc-gen-go-micro generator that has extension support for additional framework related options.

It is currently not using any registered extension number, so i want to stabilise this and i think that this is a good thing.

### CODE REVIEW

**Review by acozzette — CHANGES_REQUESTED** [review]
Could you change the number to 1143 just so that we're not skipping a number?

**Comment by vtolstov** [comment]
1142 цшдд иу гыув ин птщыешс =))

**Comment by acozzette** [comment]
Oh sorry, I missed that pulled request. This looks good to me then. I will fix the merge conflict and merge this.

**Review by acozzette — APPROVED** [review]

**Comment by vtolstov** [comment]
@acozzette thanks ! =)

**Pull request merged**
