### PR TITLE
Add async overloads for ByteString.WriteTo()

### PR DESCRIPTION
**Pull request by erikma**
Related to #3166

### CODE REVIEW

**Comment by acozzette** [comment]
CC @jskeet @anandolee 

@jtattermusch Would you be interested in reviewing this? @anandolee usually reviews C# changes but is on vacation for the next month.

**Comment by erikma** [comment]
@acozzette Would you mind adding the "C#" tag here and in my other PR? The mergeable-bot fails on that missing label, and I can't add labels

**Comment by jtattermusch** [comment]
Same as https://github.com/protocolbuffers/protobuf/pull/6230#issuecomment-500869085 can you describe the use case?
Also, on netstandard2.0 you can use the .Span property and write to an output stream (or to a pipewriter) in a more flexible fashion.

**Comment by erikma** [comment]
Good point and I'll move toward that. In this case I'm working in a net472 codebase, the .Span property is not visible in this case, so I was optimizing for what was available to minimize thread waits.

**Comment by erikma** [comment]
@jtattermusch Memory<T> only supported on netcore2.1+. I'd prefer to get this change in for downlevel net472 optimization.

**Comment by jtattermusch** [comment]
Same response as on https://github.com/protocolbuffers/protobuf/pull/6230#issuecomment-506685273

**Comment by erikma** [comment]
@jtattermusch This is different from #6230 as it simply adds the ability to write to a stream without holding a thread context. I closed that PR, but this one still seems useful by itself.

**Comment by jtattermusch** [comment]
Once we add the System.Memory dependency for all targets (see https://github.com/protocolbuffers/protobuf/pull/6317), it seems that this will no longer be useful, because you can grab byteString.Span  and use that to write to the Stream?

**Pull request closed without merging**
