### PR TITLE
Register new extension in options.md

### PR DESCRIPTION
**Pull request by johan-groenenboom**
Register options extension number for TFS TEM

### CODE REVIEW

**Comment by esrauchg** [comment]
Thanks for your contribution! You'll need to sign the CLA for us to consider accepting this PR.

**Comment by johan-groenenboom** [comment]
Thanks! I'm on it ...

**Comment by johan-groenenboom** [comment]
Still in progress to get the CLA signed - big company so these things take time ....

**Comment by googleberg** [comment]
@johan-groenenboom do you wish to proceed?

**Comment by johan-groenenboom** [comment]
Keeping this open will be resolved soon

**Comment by johan-groenenboom** [comment]
No longer required at this point in time

**Pull request closed without merging**
