### PR TITLE
Clean up mac PHP kokoro tests

### PR DESCRIPTION
**Pull request by mkruskal-google**
PHP 7.0 is no longer tested or explicitly supported, and we use homebrew to install 7.3 for the remaining test.

### CODE REVIEW

**Comment by haberman** [comment]
We should get sign-off from @bshaffer and @dwsupplee before deprecating any old version of PHP.

**Comment by mkruskal-google** [comment]
> We should get sign-off from @bshaffer and @dwsupplee before deprecating any old version of PHP.

Great, thanks Josh!  I'll ping them once this is green

**Comment by deannagarcia** [comment]
Can we prioritize getting a PR out to fix the failures in the tests and then decide whether to deprecate PHP 7.0?

**Comment by perezd** [comment]
Let's separate the two concerns here:

1.  We want to tighten our support window (I am in favor of this)
2. We need to immediately unblock our presubmit tests to ensure we're not introducing critical regressions.

Lets focus on getting point 2 taken care of asap, as we need additional time to get buyin on point 1. It is unacceptable for us be merging code without tests running for a prolonged period of time. Can we focus our efforts there primarily?

**Comment by mkruskal-google** [comment]
I was trying to take a middle ground approach here, since I thought 7.3 would be easy to fix and 7.0 wasn't worth fixing.  It turns out 7.3 was harder than I expected (because we're using such an old mac os, so disabling the tests sounds reasonable)

**Pull request closed without merging**
