### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by xiaolou86**

### CODE REVIEW

**Comment by xiaolou86** [comment]
@fowles Thanks for your review. I have signed the CLA.

**Review by fowles — APPROVED** [review]

**Comment by xiaolou86** [comment]
@fowles why did the bot close the PR? could you help to reopen it?

**Comment by fowles** [comment]
because there was an internal thing that needed updating for the spellings, I had to submit this as a separate change (https://github.com/protocolbuffers/protobuf/commit/48ebb9b0bb55c0effab41c1914436819cf4590c0) so the bot closed it when it merged that in.  You are still listed as the primary author of that change though

**Comment by xiaolou86** [comment]
Thank you very much.

**Pull request closed without merging**
