### PR TITLE
3.10.x - Remove internal constraint on descriptor proto (C#)

### PR DESCRIPTION
**Pull request by nagytech**
Cherry picking 69cb61c6 from master to help resolve some issues that I'm currently facing.  Also found that someone else was facing the same issue #5441, and noted that it may be blocking of #658.

### CODE REVIEW

**Comment by nagytech** [comment]
@ObsidianMinor I found one of your changes in master that I would like to see in the next release of the Google.Protobuf C# library.  And, according to the contribution guidelines the process for patching a release with something from master is to cherry-pick.  But, GoogleBot has identified that I'm not the author of the code in my PR, so it's currently blocked.  

Would you be able to follow the instructions above and leave the comment of `@googlebot I consent` if you're happy with the changes?

**Comment by rafi-kamal** [comment]
We just released 3.10.1. Can this change wait until 3.11?

**Comment by ObsidianMinor** [comment]
What is the expected ETA for 3.11?

**Comment by rafi-kamal** [comment]
We should have 3.11 release by Q4, but we haven't set any specific date yet.

**Comment by nagytech** [comment]
@rafi-kamal 

Regarding my ability to wait for 3.11, the best I can do is tell you why I need it - hopefully it will help.

I'm working on a polyglot framework for serverless functions which currently has Java, JavaScript, Go and working on Rust support - http://github.com/cloudstateio/cloudstate.  I'm working on the csharp implementation and it is currently blocked by this issue.

While I am happy building my own version of the Protobuf C# DLLs, it's not something that I can easily hand out to the community or to my peers to allow them to contribute.  

If it's possible to add this in easily to a 3.10.x patch, it would be appreciated.

**Comment by rafi-kamal** [comment]
Hi Jonathan!

Thanks for explaining the background. While we definitely don't want you to be blocked, doing a release comes with a few overheads, e.g. updating the versions, updating changes.txt, building protoc, uploading protoc artifacts to Maven, building all the binaries and creating a new release in GitHub with the binaries. That's why we tend to do avoid doing minor releases unless it's is a bugfix.

I understand that depending on a locally built package is never an ideal solution, but will it be reasonable for you to do that until 3.11 comes out? I'm not a C# expert but if you need help building the nuget packages, I will be able do that pretty easily using our release script. Meanwhile I'll discuss with the team to come up with a more specific timeline for 3.11.

**Comment by rafi-kamal** [comment]
@nagytech we're doing a 3.11 release sometime next week, thanks for the patience!

**Comment by rafi-kamal** [comment]
Protobuf 3.11.0-RC1 has been published to nuget.

**Pull request closed without merging**
