### PR TITLE
Fix unit tests for older rubies

### PR DESCRIPTION
**Pull request by jbolinger**
#5726 and #5659 added references to `FrozenError` and `Integer`, which were added to Ruby in 2.5 and 2.4, and will cause test failures for older rubies. This updates the tests so that they are compatible.

### CODE REVIEW

**Comment by TeBoring** [comment]
How did you find this problem?
I don't see any of our continuous test was broken.

**Comment by jbolinger** [comment]
It was mostly by accident. I was double checking that the tests passed locally when I sync'd that other PR but didn't realize that I had switched to Ruby 2.4. So, I ran them on all rubies that I have installed on my machine and found these issues.

What versions of Ruby does kokoro test with?

**Comment by jbolinger** [comment]
For example, #5751 should fail now because of this.

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf
Our continuous test are still passing.

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/blob/master/tests.sh
Could you try adding ```set -ex``` in this file in another PR?
See whether the ruby test can fail.

**Comment by jbolinger** [comment]
It looks like that file already has a `set -e` in it. I'm not sure if/how that interacts with `eval`, but I'm not sure what to change there.

Have you tried running the tests locally on 2.3?

**Comment by jbolinger** [comment]
@TeBoring looks like someone found a cleaver way to speed up the build 😄 (see #5840)

**Comment by TeBoring** [comment]
Could you sync?

**Comment by jbolinger** [comment]
@TeBoring sure, sync'd.

**Comment by haberman** [comment]
Could you sync again? Sorry, my earlier PR from today (https://github.com/protocolbuffers/protobuf/pull/5539) broke the build, but I didn't know it because a bug made it show as green. I reverted that PR so hopefully yours will pass now.

**Comment by jbolinger** [comment]
@haberman no problem, sync'd. 

Hope this gets the build back in shape. After sending #5840 it looks like that false positive build status might have been going on for awhile?

**Pull request merged**
