### PR TITLE
Remove the JavaScript implementation

### PR DESCRIPTION
**Pull request by acozzette**
This implementation is about to be split out into a separate Git repo.

### CODE REVIEW

**Review by haberman — APPROVED** [review]

**Comment by zepatrik** [comment]
I assume the new repo is https://github.com/protocolbuffers/protobuf-javascript? Or where did this go? How can I use it now?

**Comment by zepatrik** [comment]
Hm ok after two hours of research it seems this was just removed and after 3.20.1 there is no way to generate js. How is this not a breaking change??

**Comment by mayankav** [comment]
why was it removed from this repo?

**Comment by nocive** [comment]
what an absolute sh*t show

**Comment by alexeagle** [comment]
@zepatrik yes, https://github.com/protocolbuffers/protobuf-javascript is the new repo.

**Comment by szigetics** [comment]
A possible solution is shared here : https://github.com/protocolbuffers/protobuf-javascript/issues/127#issuecomment-1204202870

**Comment by pietrodn** [comment]
There is an official first-party solution: if you `npm install grpc-tools`, then you simply use `grpc_tools_node_protoc` (which is inside `node_modules/.bin`) instead of `protoc`. See [documentation](https://www.npmjs.com/package/grpc-tools).

This way I managed to do without [protoc-gen-js](https://www.npmjs.com/package/protoc-gen-js).

**Pull request merged**
