### PR TITLE
Fix a typo in the README

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by acozzette** [comment]
Thanks, @peternewman.

**Comment by peternewman** [comment]
No worries @acozzette .

Running codespell finds a few more:
https://github.com/peternewman/protobuf/actions/runs/179888426

I can fix those.

Are you also interested in having codespell as a permanent action annotating future spelling mistakes?

**Comment by acozzette** [comment]
If you want to send another PR to fix more spelling mistakes then that would be great. I think for now I would prefer not to add the permanent action, though--that sounds nice to have but at the moment I'm not sure I have time to learn about configuring GitHub actions.

**Comment by peternewman** [comment]
> If you want to send another PR to fix more spelling mistakes then that would be great.

Okay @acozzette see #7751 .

> I think for now I would prefer not to add the permanent action, though--that sounds nice to have but at the moment I'm not sure I have time to learn about configuring GitHub actions.

You don't need to learn, you'd just need to hit merge on #7752 and it would just work and automatically annotate PRs with typos it found (when the other blockers in the PR are resolved).

**Pull request merged**
