### PR TITLE
Build extensions for Ruby 2.7

### PR DESCRIPTION
**Pull request by qnighy**
I've made two groundworks for building protobuf extensions for Ruby 2.7:

- Reporting ruby issue at https://bugs.ruby-lang.org/issues/16384, which was fixed in https://github.com/ruby/ruby/commit/40026a408df5e3576380f6c1d8bf6c119fa2e32b
- Reporting rake-compiler issue at https://github.com/rake-compiler/rake-compiler/pull/161, which was fixed in https://github.com/rake-compiler/rake-compiler/commit/6822686f0c45e752974de02a980365515e843267

Now that 2.7.0-rc2 has been released, can we start building extensions for Ruby 2.7?

### CODE REVIEW

**Comment by casperisfine** [comment]
@haberman sorry for the ping, but any change for this to be merged ?

**Comment by haberman** [comment]
No worries about the ping, please take a look at the test failures. Feel free to ping me again.

**Comment by qnighy** [comment]
Ah OK, the CI doesn't run automatically.

**Comment by qnighy** [comment]
From https://source.cloud.google.com/results/invocations/ac6df955-314c-45f7-8e2e-a9a2cbfdedbc/targets/protobuf%2Fgithub%2Fmaster%2Fubuntu%2Fruby_release%2Fpresubmit/log ...

```
/usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
	from /usr/local/rvm/gems/ruby-2.5.3/bin/bundle:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	from /usr/local/rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
rake aborted!
Command failed with status (1): [docker run -v /tmpfs/src/github/protobuf/ruby:/tmpfs/src/github/protobuf/ruby -e UID\=1000 -e GID\=1000 -e USER\=kbuilder -e GROUP\=kbuilder -e ftp_proxy\= -e http_proxy\= -e https_proxy\= -e RCD_HOST_RUBY_PLATFORM\=x86_64-linux -e RCD_HOST_RUBY_VERSION\=2.4.1 -e RCD_IMAGE\=protobuftesting/ruby_rake_compiler_52bbc96c6d72ba1b25e99e19bdcfeb240438566c -w /tmpfs/src/github/protobuf/ruby --rm -i protobuftesting/ruby_rake_compiler_52bbc96c6d72ba1b25e99e19bdcfeb240438566c runas sigfw bash -c bundle\ \&\&\ IN_DOCKER\=true\ rake\ cross\ native\ gem\ RUBY_CC_VERSION\=2.7.0:2.6.0:2.5.0:2.4.0:2.3.0]
```

I guess there's a mismatch in bundler versions? one is from `kokoro/linux/dockerfile/release/ruby_rake_compiler/Dockerfile` and the other is from somewhere before `kokoro/release/ruby/linux/ruby/ruby_build.sh`.

**Comment by casperisfine** [comment]
> I guess there's a mismatch in bundler versions?

Yeah that's a classic error with Ruby 2.7

**Comment by qnighy** [comment]
I'm still not sure where `bundler ~> 1.0` is required, but as `rake-compiler-dock >= 7.1` does something related to bundler versions, I'd like to see what happens when the gem is upgraded to the latest version.

**Comment by qnighy** [comment]
@haberman could you rerun the CI again? Thanks in advance!

**Comment by haberman** [comment]
Seems to still be failing?

I'm not an expert on the Ruby build infrastructure, so not sure I can be much help here, sorry!

**Comment by casperisfine** [comment]
I'm having a hard time to reproduce locally, however I figured one of the issues, it's a bug in rake-compiler-dock 1.0.0, I opened a PR to fix it: https://github.com/rake-compiler/rake-compiler-dock/pull/31

**Comment by haberman** [comment]
Looks like https://github.com/rake-compiler/rake-compiler-dock/pull/31 is fixed upstream.

If we upgrade to rake-compiler-dock 1.0.1, perhaps the tests will pass?

**Comment by haberman** [comment]
@qnighy do you want to update this to use rake-compiler-dock 1.0.1?

**Comment by Jesterovskiy** [comment]
I really need these changes, because I can't install stackdriver =( https://github.com/googleapis/google-cloud-ruby/issues/5110

**Comment by qnighy** [comment]
> @qnighy do you want to update this to use rake-compiler-dock 1.0.1?

I tried upgrading them in the gemspec. Could you kick CI once again?

**Comment by haberman** [comment]
@qnighy Looks like we're still getting an error. :(

```
/Users/kbuilder/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/x86_64-darwin18/rbconfig.rb:13:in `<module:RbConfig>': ruby lib version (2.7.0) doesn't match executable version (2.6.0) (RuntimeError)
	from /Users/kbuilder/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/x86_64-darwin18/rbconfig.rb:11:in `<top (required)>'
	from /Users/kbuilder/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/fileutils.rb:4:in `require'
	from /Users/kbuilder/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/fileutils.rb:4:in `<top (required)>'
	from /Users/kbuilder/.rake-compiler/sources/ruby-2.6.0/tool/transform_mjit_header.rb:5:in `require'
	from /Users/kbuilder/.rake-compiler/sources/ruby-2.6.0/tool/transform_mjit_header.rb:5:in `<main>'
make: *** [.ext/include/x86_64-darwin11/rb_mjit_min_header-2.6.0.h] Error 1
```

**Comment by qnighy** [comment]
https://github.com/grpc/grpc/commit/4c667476a096f1f248d5cca0c3b510ea6040c984 do we perhaps need to get rid of `grpctesting/rake-compiler-dock_53c22085d091183c528303791e7771359f699bcf`?

**Comment by qnighy** [comment]
@haberman I'd like to see what happens when I remove the custom RCD image. Could you kick the CI again?

**Comment by qnighy** [comment]
Okay, this change must be important: https://github.com/grpc/grpc/commit/4c667476a096f1f248d5cca0c3b510ea6040c984#diff-52c976fc38ed2b4e3b1192f8a8e24cffL131-R150

@haberman one more kick, please? Thanks in advance!

**Comment by haberman** [comment]
Looks like we're still getting an error:

```
/Users/kbuilder/.rvm/rubies/ruby-2.7.0/bin/ruby --disable=gems -I/Users/kbuilder/.rake-compiler/builds/x86_64-darwin11/ruby-2.6.0 -rx86_64-darwin11-fake  /Users/kbuilder/.rake-compiler/sources/ruby-2.6.0/tool/transform_mjit_header.rb "clang " rb_mjit_header.h .ext/include/x86_64-darwin11/rb_mjit_min_header-2.6.0.h
/Users/kbuilder/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/x86_64-darwin18/rbconfig.rb:13:in `<module:RbConfig>': ruby lib version (2.7.0) doesn't match executable version (2.6.0) (RuntimeError)
	from /Users/kbuilder/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/x86_64-darwin18/rbconfig.rb:11:in `<top (required)>'
	from /Users/kbuilder/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/fileutils.rb:4:in `require'
	from /Users/kbuilder/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/fileutils.rb:4:in `<top (required)>'
	from /Users/kbuilder/.rake-compiler/sources/ruby-2.6.0/tool/transform_mjit_header.rb:5:in `require'
	from /Users/kbuilder/.rake-compiler/sources/ruby-2.6.0/tool/transform_mjit_header.rb:5:in `<main>'
make: *** [.ext/include/x86_64-darwin11/rb_mjit_min_header-2.6.0.h] Error 1
```

Do you think it's worth trying `ruby-install` and `chruby` instead of `rvm`?
- https://github.com/postmodern/ruby-install
- https://github.com/postmodern/chruby instead

In my experience, `ruby-install` and `chruby` (along with `bundle exec`) have been really solid ways of switching between Ruby versions.

**Comment by qnighy** [comment]
> Do you think it's worth trying `ruby-install` and `chruby` instead of `rvm`?

I'll instead follow the grpc/grpc's approach: https://github.com/grpc/grpc/commit/09bc1eebe491f8e74c263ffe13257369c467c533

**Comment by qnighy** [comment]
I guess when I update dockerfiles in `kokoro/linux/dockerfile/test`, someone with a certain privilege has to invoke `kokoro/linux/dockerfile/push_testing_images.sh` manually?

Then, in this PR, I'd like to focus on building extensions for Ruby 2.7. I'll prepare another PR for testing protobuf in Ruby 2.7.

**Comment by qnighy** [comment]
@haberman can it be merged? I think the remaining CI failures are unrelated to this PR.

スクリーンショット 2020-04-17 14 22 03

**Comment by qnighy** [comment]
Thanks a lot! I'm really glad to see this merged.

**Pull request merged**
