### PR TITLE
Update third_party.md with Monkey C implementation

### PR DESCRIPTION
**Pull request by JCampbell8**
Monkey C protobuf compiler plugin + protobuf runtime barrel

### CODE REVIEW

**Comment by JCampbell8** [comment]
@googlebot I signed it!

**Comment by JCampbell8** [comment]
I've signed the CLA, not sure how to proceed.

**Comment by acozzette** [comment]
@JCampbell8 I think the reason for the CLA check not going through is that the email address you use to sign the CLA has to be set on the Git commit. If you amend the commit to add your email address then that should solve the problem.

**Comment by acozzette** [comment]
I am going to close this pull request because it has gone a while without being updated, and our CLA bot has been unable to verify that the CLA was signed. If you're still interested in working on this change and are willing to sign the CLA, please comment here and I can try to help sort out the problem.

**Pull request closed without merging**
