### PR TITLE
Add support for loongarch64

### PR DESCRIPTION
**Pull request by zhaixiaojuan**
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.

Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html

### CODE REVIEW

**Comment by jorgbrown** [comment]
We'd prefer not to explicitly list every possible architecture.

I tested using the loongarch64 gcc compiler; see <https://godbolt.org/z/9Er7Yac6o> and it appears that we already do the right thing, with regards to detecting whether it's 64-bit...

What problem are you seeing right now?

ps Are you aware of https://github.com/protocolbuffers/protobuf/pull/11438 ?

**Comment by zhaixiaojuan** [comment]
> We'd prefer not to explicitly list every possible architecture.
> 
> I tested using the loongarch64 gcc compiler; see https://godbolt.org/z/9Er7Yac6o and it appears that we already do the right thing, with regards to detecting whether it's 64-bit...
> 
> What problem are you seeing right now?
> 
> ps Are you aware of #11438 ?

sorry, I will close this PR.

**Comment by zhaixiaojuan** [comment]
Hello, I would like to ask whether the release under the protobuf project can add the binary package of loongarch64. Or what efforts do we need to make this happen?

**Comment by Panxuefeng-loongson** [comment]
> Hello, I would like to ask whether the release under the protobuf project can add the binary package of loongarch64. Or what efforts do we need to make this happen?

It looks like protobuf is important to the LoongArch architecture, but the community may be short of building machines. docker + qume might be a viable option, but it will increase maintenance overheads. I wonder what your opinion is on this. @jorgbrown

**Comment by zhaixiaojuan** [comment]
Is the following approach possible?
We provide build machines locally, set up CI build process, and perform remote builds.

**Pull request closed without merging**
