### PR TITLE
add null check to equals

### PR DESCRIPTION
**Pull request by PartialDragster**
added a null check to equals implementation so that it matches the method's contract

### CODE REVIEW

**Comment by PartialDragster** [comment]
@googlebot I signed it!

**Comment by PartialDragster** [comment]
Okay, says it needs a label but I have NO idea how to add one...

**Comment by perezd** [comment]
What contract are you referencing? I don't think this change immediately makes sense to me, if you pass `null` to equals it should return a boolean and `false`.

**Comment by PartialDragster** [comment]
Ugh sorry that was a stupid mistake. Yes supposed to return `false' not `null`. 

I was submitting based on the result of static checks we got back on work but I just double checked and see that if `null` is provided as the LHS of `instanceof` it returns `false` (TIL) as you'd expect so it looks like their check is wrong. I'll feed that back to them. 

Sorry for the noise!

Hmmm although it looks like it might be possible to get an NRE a little later in the method though. It looks like it's possible for `fields` to be `null` so the expression `fields.equals(((UnknownFieldSet)other).fields)` will error if the `fields` on the given object is `null`. I'll submit a PR for that sometime today.

**Pull request closed without merging**
