### PR TITLE
Avoid duplicate variable name when unity build

### PR DESCRIPTION
**Pull request by mkkim1129**
Fix https://github.com/protocolbuffers/protobuf/issues/7770

### CODE REVIEW

**Comment by mkkim1129** [comment]
@googlebot I signed it!

**Comment by mkkim1129** [comment]
@googlebot I fixed it.

**Comment by mkkim1129** [comment]
@googlebot I fixed it.

**Comment by acozzette** [comment]
Sorry but I don't think we can accept this pull request. Making pb.cc files safe to concatenate together would create a new maintenance burden that we don't want to take on. I actually think including pb.cc files in unity builds would probably make incremental rebuilds slower most of the time, since if you're just editing C++ source then there's no need to rebuild the pb.cc code. If you want to do a unity build I would suggest excluding the pb.cc files from it.

**Pull request closed without merging**
