### PR TITLE
Bugfix/issue 8101

### PR DESCRIPTION
**Pull request by tonydnewell**
Fix for https://github.com/protocolbuffers/protobuf/issues/8101

When converting identifiers for C# camel case, handle the case where the input starts with "_&lt;digit&gt;" and preserve the underscore.

It does not alter existing behaviour for other identifiers:
- e.g. starts with "_&lt;alpha&gt;" - the underscore is consumed, so as to not break anything that relies on existing behaviour.
- e.g. input is already invalid (e.g. identifier starts with a digit) -  it does not try and fix it.

### CODE REVIEW

**Review by jskeet — APPROVED** [review]

**Review by jskeet — APPROVED** [review]

**Review by fowles — APPROVED** [review]

**Review by jtattermusch — COMMENTED** [review]
LGTM as well.

**Comment by nickwinger** [comment]
@tonydnewell  thank you for this fix, but on our side there is still a similar bug open with this, e.g.: namespace "my.space._3" gets compiled to c# "my.space.3" which again causes an error. So also with "sub" namespaces after dots the numbers with an underscore should be preserved. thank you

**Comment by tonydnewell** [comment]
@nickwinger Thank you for your observation. I can see you've created a new issue https://github.com/protocolbuffers/protobuf/issues/13482
I can't guarantee when it will be fixed but it is on the list.

**Comment by nickwinger** [comment]
here is the PR: https://github.com/protocolbuffers/protobuf/pull/13504

**Pull request merged**
