### PR TITLE
Fix: Undefined behavior in UTF8GenericScanFastAscii

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Fixes https://github.com/protocolbuffers/protobuf/issues/5984.

Pl. let me know if you prefer different error handling.

### CODE REVIEW

**Comment by acozzette** [comment]
@tapaswenipathak Thanks for the fix but we need a solution that doesn't use exceptions (we don't use exceptions in the C++ codebase). I think it's also valid for the string to be less than 7 bytes long, so we need to handle that case.

**Comment by tapaswenipathak** [comment]
Yea, perfect. That's :fire: :slightly_smiling_face:

I will write the code fix.

**Comment by tapaswenipathak** [comment]
Yea, right, ko; that's a unique item I missed, lol.

I will write the code fix.

**Comment by tapaswenipathak** [comment]
@acozzette: 

There are few options
- Use https://en.cppreference.com/book/intro/smart_pointers.
- Append null characters in the string, make sure the string size atleast 7
- Check for dangling pointer
- Add a log statement
- Throw an exception

Do you have any notes/thoughts?

**Comment by acozzette** [comment]
Actually I think there is an easy way to solve it. If there are fewer than 7 bytes in the array then srclimit8 should just point to the beginning of the array. I haven't tested this but I believe something like this would work:

`const uint8* srclimit8 = str_length < 7 ? isrc : srclimit - 7;`

**Comment by tapaswenipathak** [comment]
Agreed.

**Comment by acozzette** [comment]
Thanks, @tapaswenipathak!

**Pull request merged**
