### PR TITLE
Display beta version in "protoc --version"

### PR DESCRIPTION
**Pull request by saurabhs2501**
Display the beta version when "protoc --version" is executed. Use
PROTOBUF_VERSION_SUFFIX for this purpose. #1639

### CODE REVIEW

**Comment by acozzette** [comment]
@saurabhs2501 Thank you for the pull request. The one problem I see is that we have not updated `PROTOBUF_VERSION_SUFFIX` in a long time. I think `update_version.py` needs to update it, because we rely on that script for updating the version numbers everywhere they appear. Could you edit that script to make it update `PROTOBUF_VERSION_SUFFIX`?

**Comment by saurabhs2501** [comment]
@acozzette I have updated `update_version.py` to update `PROTOBUF_VERSION_SUFFIX`

**Comment by saurabhs2501** [comment]
@acozzette I am looking at the build failures. One particular failure(MacOS Python C++) fails with this:

```
sudo: unable to execute /Library/Frameworks/Python.framework/Versions/3.7/bin/pip: No such file or directory
```

Not sure what I need to do about this.

**Comment by acozzette** [comment]
@saurabhs2501 Thanks!

**Pull request merged**
