### PR TITLE
Remove unrecognized fields from args to `rust_common.crate_info`

### PR DESCRIPTION
**Pull request by tempoz**

### CODE REVIEW

**Comment by acozzette** [comment]
@tempoz I see a couple of CI failures but I suspect those are just caused by your branch being a bit behind main. Sorry for the trouble but would you mind merging main into your branch (or rebasing)?

**Comment by tempoz** [comment]
Done!

**Review by acozzette — APPROVED** [review]

**Comment by JasonLunn** [comment]
@tempoz - apologies, but a merge conflict has crept into this branch. Can you resolve?

**Comment by tempoz** [comment]
Another change apparently fixed this, so the rebase emptied the branch. Problem resolved!

**Pull request closed without merging**
