### PR TITLE
Integrate from Piper for C++, Java, and Python

### PR DESCRIPTION
**Pull request by haberman**
**Important**: this integration must be merged, not squashed!

### CODE REVIEW

**Comment by haberman** [comment]
This fixes https://github.com/protocolbuffers/protobuf/issues/7463

**Comment by haberman** [comment]
Merging. Heads up to @jtattermusch and @jskeet that there's a new conformance test here that C# is failing, related to proto2 and JSON. May want to look at it at some point.

**Comment by jskeet** [comment]
@haberman: Thanks, will try to look next week.

**Comment by jskeet** [comment]
See #7486 and #7487 for the C# conformance test part.

**Pull request merged**
