### PR TITLE
JS: parse (un)packed fields conditionally

### LINKED ISSUE #1701: JavaScript parser fails to parse packed repeated field as not packed (and vice versa)
### Message definitions

`proto2_test.proto`:

```
syntax = "proto2";

package test;

message Test2Int32RepPackedTrue {
    repeated int32 repeated_int32 = 1 [packed = true];
}

message Test2Int32RepPackedFalse {
    repeated int32 repeated_int32 = 1 [packed = false];
}
```

`proto3_test.proto` (same as above but with `proto3` instead of `proto2` and `Test3*` instead of `Test2`:

```
syntax = "proto3";

package test;

message Test3Int32RepPackedTrue {
    repeated int32 repeated_int32 = 1 [packed = true];
}

message Test3Int32RepPackedFalse {
    repeated int32 repeated_int32 = 1 [packed = false];
}
```

Compiled via:

```
$ protoc --version
libprotoc 3.0.0
$ protoc --js_out=import_style=commonjs,binary:. *.proto
```
### JavaScript Test

Test script which first serializes examples of the four message types defined above and then tries to deserialize each of them using all four message types. Expected behavior: deserialization works in all cases.

`packed_test.js`:

```
var test2_pb = require('./test/proto2_test_pb');
var test3_pb = require('./test/proto3_test_pb');

var plRepInt32 = [42];

functions = [test2_pb.Test2Int32RepPackedTrue, test2_pb.Test2Int32RepPackedFalse, test3_pb.Test3Int32RepPackedTrue, test3_pb.Test3Int32RepPackedFalse]
names = ["Proto2 packed=true", "Proto2 packed=false", "Proto3 packed=true", "Proto3 packed=false"]

for (var i = 0; i < functions.length; i++) {
    var src = functions[i];
    for (var j = 0; j < functions.length; j++) {
        var dst = functions[j];
        var msg = new src();
        msg.setRepeatedInt32List(plRepInt32);
        var bytes = msg.serializeBinary();
        try {
            dst.deserializeBinary(bytes);
        } catch (e) {
            console.log("deserialize failed src: " + names[i] + " dst: " + names[j]);
        }
    }
}
```

Using `google-protobuf` version `3.0.0-alpha.6` via `npm`.
### Output

```
$ node packed_test.js 
deserialize failed src: Proto2 packed=true dst: Proto2 packed=false
deserialize failed src: Proto2 packed=true dst: Proto3 packed=false
deserialize failed src: Proto2 packed=false dst: Proto2 packed=true
deserialize failed src: Proto2 packed=false dst: Proto3 packed=true
deserialize failed src: Proto3 packed=true dst: Proto2 packed=false
deserialize failed src: Proto3 packed=true dst: Proto3 packed=false
deserialize failed src: Proto3 packed=false dst: Proto2 packed=true
deserialize failed src: Proto3 packed=false dst: Proto3 packed=true
```
### Result

Parsing (not) packed as (not) packed messages works correctly.
Parsing packed as not packed messages (and vice versa) does not work although [it should](https://developers.google.com/protocol-buffers/docs/encoding#packed).
### Stacktraces

Parse packed as not packed:

```
AssertionError: Assertion failed
    at new goog.asserts.AssertionError (/home/epg/halde/protobuf_test/node_modules/google-protobuf/google-protobuf.js:62:603)
    at Object.goog.asserts.doAssertFailure_ (/home/epg/halde/protobuf_test/node_modules/google-protobuf/google-protobuf.js:63:126)
    at Object.goog.asserts.assert [as assert] (/home/epg/halde/protobuf_test/node_modules/google-protobuf/google-protobuf.js:63:385)
    at jspb.BinaryReader.readInt32 (/home/epg/halde/protobuf_test/node_modules/google-protobuf/google-protobuf.js:234:371)
    at Function.proto.test.Test2Int32RepPackedFalse.deserializeBinaryFromReader (/home/epg/halde/protobuf_test/test/proto2_test_pb.js:453:49)
    at Function.proto.test.Test2Int32RepPackedFalse.deserializeBinary (/home/epg/halde/protobuf_test/test/proto2_test_pb.js:434:46)
    at Object.<anonymous> (/home/epg/halde/protobuf_test/packed_test.js:17:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
```

Parse not packed as packed:

```
AssertionError: Assertion failed
    at new goog.asserts.AssertionError (/home/epg/halde/protobuf_test/node_modules/google-protobuf/google-protobuf.js:62:603)
    at Object.goog.asserts.doAssertFailure_ (/home/epg/halde/protobuf_test/node_modules/google-protobuf/google-protobuf.js:63:126)
    at Object.goog.asserts.assert [as assert] (/home/epg/halde/protobuf_test/node_modules/google-protobuf/google-protobuf.js:63:385)
    at jspb.BinaryReader.readPackedField_ (/home/epg/halde/protobuf_test/node_modules/google-protobuf/google-protobuf.js:243:71)
    at jspb.BinaryReader.readPackedInt32 (/home/epg/halde/protobuf_test/node_modules/google-protobuf/google-protobuf.js:243:357)
    at Function.proto.test.Test2Int32RepPackedTrue.deserializeBinaryFromReader (/home/epg/halde/protobuf_test/test/proto2_test_pb.js:280:58)
    at Function.proto.test.Test2Int32RepPackedTrue.deserializeBinary (/home/epg/halde/protobuf_test/test/proto2_test_pb.js:261:45)
    at Object.<anonymous> (/home/epg/halde/protobuf_test/packed_test.js:17:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

### PR DESCRIPTION
**Pull request by qnighy**
The current JS implementation doesn't comply with the following criteria:

> Note that although there's usually no reason to encode more than one key-value pair for a packed repeated field, encoders must be prepared to accept multiple key-value pairs. In this case, the payloads should be concatenated. Each pair must contain a whole number of elements.
> https://developers.google.com/protocol-buffers/docs/encoding#packed

> Protocol buffer parsers must be able to parse repeated fields that were compiled as `packed` as if they were not packed, and vice versa. This permits adding `[packed=true]` to existing fields in a forward- and backward-compatible way.
>
> https://developers.google.com/protocol-buffers/docs/encoding#packed

In this PR, the parser checks `WireType` before parsing packable fields, and then always append to the existing array, instead of replacing it.

Fixes #1701.

### CODE REVIEW

**Comment by qnighy** [comment]
I'd like to ask how to add tests for this; it looks like the existing tests just encode a value and then decode it and don't embed a protobuf binary for testing? Is there any reason not embedding something like `[0x7a, 0x0a, 0x08, 0x9b, 0xb5, 0x08, 0xa0, 0x06, 0x01, 0xa8, 0x06, 0x01]`?

**Comment by qnighy** [comment]
@TeBoring

**Comment by qnighy** [comment]
@TeBoring I removed the relevant lines from `conformance/failure_list_js.txt` to enable conformance tests. Is this enough?

**Comment by qnighy** [comment]
@TeBoring we're occasionally hit by this problem (since our JavaScript client communicates with Ruby servers, where the current implementation always encodes repeated fields unpacked). It's great if you have time to look at this.

**Comment by qnighy** [comment]
@haberman sorry for the sudden mention, but could you or someone else look at this? The diff is essentially about 30 lines and it should be relatively easy to review...

We're actively applying changes to our internal protobuf messages which are sent between JS and Ruby, and #1701 is a real annoyance since failing to `[packed = false]` to a newly defined repeated scalar field ruins everything.

**Comment by izumin5210** [comment]
@haberman @TeBoring @dlj-NaN can you help to review?

**Comment by qnighy** [comment]
@haberman thanks for reviewing and kicking the CI! The only failures are Java things (which I think is unrelated to this PR) and the lack of language label (which I cannot help), so I guess there's nothing I can do now. Right?

スクリーンショット 2020-08-20 11 39 42

**Comment by qnighy** [comment]
@haberman could you merge this?

**Pull request merged**
