### PR TITLE
test(php):php json_encode empty ListValue test case.

### PR DESCRIPTION
**Pull request by lightjiao**
Add php test case.

### CODE REVIEW

**Comment by lightjiao** [comment]
I cannot run `./test.sh php7.2` or `cd php && composer install && composer test` command to test in local.

Any way I can test it in local ?

**Comment by lightjiao** [comment]
I cp my last fix to this pr, it look good for me, but I don't know how to run unit test

by the way, I think my fix is not very good, I think should fix the `_deserializeResponse` function, when parse empty `ListValue`'s desc, but this is too hard for me, and would spend lot of my time. 

Could you fix this issue as soon as possible ?
If you think my fix is not good, I would to change this pr.
thx.🙂

**Comment by lightjiao** [comment]
well, I only pr the test case.😂

**Comment by TeBoring** [comment]
Fixed in #5192

**Pull request closed without merging**
