### PR TITLE
Add version number to generated files

### PR DESCRIPTION
**Pull request by alielbashir**
This adds the version of the protoc compiler that generated the python files to the header of the generated files as specified in #11085

Edit: this PR now includes
- Python
- C++
- Java
- C#
- Objective C
- Ruby
- PHP

### CODE REVIEW

**Comment by alielbashir** [comment]
If this feature is also wanted for the other languages should I include that within this PR, or should different PRs be opened for each language?

**Comment by deannagarcia** [comment]
> If this feature is also wanted for the other languages should I include that within this PR, or should different PRs be opened for each language?

It would be great if you could add them to this PR!

**Comment by alielbashir** [comment]
I've noticed there are unit tests in the ruby compiler directory. From what I understand they compare output to the expected files in that dir. This will break that test, and will make it hard to maintain it in the future as the output will change with every new version. 

1. Are there similar tests for the other languages as well? If so how should I move forward with this so that they don't fail, while not making them a maintenance issue?
2. Should I contribute this change to the Go, JavaScript, and Dart compilers too, given that they're in other repos?

**Review by deannagarcia — APPROVED** [review]

**Comment by deannagarcia** [comment]
> I've noticed there are unit tests in the ruby compiler directory. From what I understand they compare output to the expected files in that dir. This will break that test, and will make it hard to maintain it in the future as the output will change with every new version.

> 1. Are there similar tests for the other languages as well? If so how should I move forward with this so that they don't fail, while not making them a maintenance issue?

Talked with the team about this and we are going to create an easier way to update the expected output for changes like this to decrease the maintenance burden. Can you make the manual change for the Ruby expected files for this time though?


> 2. Should I contribute this change to the Go, JavaScript, and Dart compilers too, given that they're in other repos?

Up to you, we don't work on those repos and it's not organized the same so it may be a bit of extra work for you but I think those repo managers would appreciate it.

**Comment by alielbashir** [comment]
> Talked with the team about this and we are going to create an easier way to update the expected output for changes like this to decrease the maintenance burden. Can you make the manual change for the Ruby expected files for this time though?

Done

**Comment by deannagarcia** [comment]
I think you also need to run [generate_descriptor_proto.sh](https://github.com/protocolbuffers/protobuf/blob/8870581adf5d95988bcc995a870972caa8d63e8c/generate_descriptor_proto.sh) to update C++ tests that compare the generated output.

**Comment by deannagarcia** [comment]
Sorry I'm just getting back to this, can you update your branch and fix conflicts so I can rerun the tests?

**Comment by alielbashir** [comment]
Done, please let me know if there's anything else I need to do

**Review by deannagarcia — APPROVED** [review]

**Comment by haberman** [comment]
Could you rebase this PR against the main branch? Sorry for the trouble, you caught us in the middle of a migration to GitHub Actions.

**Comment by alielbashir** [comment]
Sure thing, doing it now

**Comment by alielbashir** [comment]
Apologies, I accidentally pushed an incorrect rebase, which could be the reason for the protobuf-btr and protobuf-docs teams' review requests

**Comment by alielbashir** [comment]
@deannagarcia it seems that the PR isn't passing the safety check despite having the "safe for tests" label. Is this intentional, if so is there something else I should do on my part? Thanks

**Comment by alielbashir** [comment]
@deannagarcia any updates regarding this PR?

**Pull request closed without merging**
