### PR TITLE
Enforce recursion depth checking for unknown fields

### PR DESCRIPTION
**Pull request by jtattermusch**
See b/147012414 for details.

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @jskeet @ObsidianMinor

**Comment by jtattermusch** [comment]
Friendly ping?

**Comment by jskeet** [comment]
(I'm not going to have time to look at this myself, I'm afraid. I'm deep in a backlog of many things.)

**Comment by anandolee** [comment]
Dist failure related to another PR, it will be fixed soon

**Comment by acozzette** [comment]
It looks like all the test failures are unrelated and most seem to be a Docker issue: https://forums.docker.com/t/docker-pull-causes-error-response-from-daemon-unexpected-eof/88608

**Pull request merged**
