### PR TITLE
Improvement: Changed to add setter method when message type 'map'

### PR DESCRIPTION
**Pull request by howyi**
The current javascript-protoc is in a state where the setter method is not generated in the map field.
Merging this PR will add a setter method to the map.

## sample proto
```proto
syntax = "proto3";

package book;

message UpdateBooksRequest {
    map<uint64, Book> books = 1;
}

message Book {
    uint64 id = 1;
    string name = 2;
}

```

## current `BooksMap` methods
```javascript
/**
 * map<uint64, Book> books = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.book.Book>}
 */
proto.book.UpdateBooksRequest.prototype.getBooksMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.book.Book>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.book.Book));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.book.UpdateBooksRequest} returns this
 */
proto.book.UpdateBooksRequest.prototype.clearBooksMap = function() {
  this.getBooksMap().clear();
  return this;};
```

## new `BooksMap` methods
```javascript
/**
 * map<uint64, Book> books = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.book.Book>}
 */
proto.book.UpdateBooksRequest.prototype.getBooksMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.book.Book>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.book.Book));
};


/**
 * @param {!Object<number,!proto.book.Book>} value
 * @return {proto.book.UpdateBooksRequest}
 */
proto.book.UpdateBooksRequest.prototype.setBooksMap = function(value) {
  var map = jspb.Message.getMapField(this, 1, false,
      proto.book.Book);
  Object.keys(value).forEach((key) => {
      map.set(key, value[key])
  })
  return this;
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.book.UpdateBooksRequest} returns this
 */
proto.book.UpdateBooksRequest.prototype.clearBooksMap = function() {
  this.getBooksMap().clear();
  return this;};
```

### CODE REVIEW

**Comment by howyi** [comment]
@googlebot I signed it!

**Review by elharo — DISMISSED** [review]
needs tests

**Comment by howyi** [comment]
@elharo @lukesandberg  I modified the argument a little.
Please rerun the test and review it 🙇🏿

**Comment by elharo** [comment]
API additions require a proposal and a Tier 2 review before PRs can be considered.

**Pull request closed without merging**
