### PR TITLE
Add GenerateClassFromObject to Javascript gen

### LINKED ISSUE #1591: JS generator missing jspb.generate_from_object option
The comment for [jspb.Message.GENERATE_FROM_OBJECT](https://github.com/google/protobuf/blob/master/js/message.js#L151) states:

>  *     NOTE: By default no protos actually have a fromObject method. You need to
>  *     add the jspb.generate_from_object options to the proto definition to
>  *     activate the feature.

However, no such option is currently implemented in the open sourced version. I see the code which generates output for this option (`GenerateClassFromObject`) but it is invoked 0 times.

> ~/protobuf$ grep -r GenerateClassFromObject .
> ./src/google/protobuf/compiler/js/js_generator.cc:void Generator::GenerateClassFromObject(const GeneratorOptions& options,
> ./src/google/protobuf/compiler/js/js_generator.h:  void GenerateClassFromObject(const GeneratorOptions& options,

Can the jspb.generate_from_object option be open sourced?

### PR DESCRIPTION
**Pull request by hermanbanken**
I was astounded by #1591 being open for 4 years after its creation. It seems that everyone using Javascript with Protobuf wants to have this.

Just created this PR, by taking the source edits from https://github.com/protocolbuffers/protobuf/issues/1591#issuecomment-414778829. 🤞 that the build succeeds.

Fixes #1591

### CODE REVIEW

**Comment by hermanbanken** [comment]
Credit where it is due @parano.

**Comment by ideasculptor** [comment]
Can you update your PR so that it is mergeable again?  Maybe they'll eventually decide to do something about it?

**Comment by HypeillingerChillinger** [comment]
@hermanbanken 
Your PR contains exactly what I missed. Unfortunately I have no clue how to build the project. Can you give some advice how to do it?

**Comment by chughes-pika** [comment]
> @hermanbanken Your PR contains exactly what I missed. Unfortunately I have no clue how to build the project. Can you give some advice how to do it?

Not sure if you still need this, but the deatils are in the `src/README.md` of the proto library.  In short,
```
./configure
make
make check
make install
```

**Comment by HypeillingerChillinger** [comment]
> > @hermanbanken Your PR contains exactly what I missed. Unfortunately I have no clue how to build the project. Can you give some advice how to do it?
> 
> Not sure if you still need this, but the details are in the `src/README.md` of the proto library. In short,
> 
> ```
> ./configure
> make
> make check
> make install
> ```

Thank you.

**Comment by psigen** [comment]
@hermanbanken I rebased your PR onto the new split repo:

https://github.com/protocolbuffers/protobuf-javascript/pull/6

I don't know if that will help it get any traction, but at least it's there again.

**Comment by acozzette** [comment]
@psigen Thank you for transferring over the change, let me go ahead and close this one since the code has moved.

**Pull request closed without merging**
