### PR TITLE
Ignore make.sh

### PR DESCRIPTION
**Pull request by songy23**

### CODE REVIEW

**Comment by acozzette** [comment]
Where does this `make.sh` file come from? I can't remember ever seeing that file appear.

**Comment by songy23** [comment]
After running the C++ installation instructions (https://github.com/protocolbuffers/protobuf/blob/master/src/README.md#c-installation---unix):
> $ ./configure
$ make
$ make check
$ sudo make install
$ sudo ldconfig # refresh shared library cache.

Then I saw
```bash
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	make.sh
```

**Comment by acozzette** [comment]
That's interesting, I have never seen that file before and I can't find any documentation referencing it. I guess adding it to the `.gitignore` theoretically can't hurt but I am still curious to know what it is first. Could you post the contents of the file?

**Comment by songy23** [comment]
Apologies, for some reason I cannot reproduce this when running the installation commands again (the original file was removed with `git clean`). I guess this is a temporary intermediate file generated by the commands. I'll come back update this PR if I saw this file again.

**Pull request closed without merging**
