### PR TITLE
Added Embedded Proto to third_party.md.

### PR DESCRIPTION
**Pull request by BartHertog**
Added Embedded Proto as a new option in the third_party.md file.

### CODE REVIEW

**Comment by BartHertog** [comment]
@googlebot I signed it!

**Comment by acozzette** [comment]
@BartHertog Sorry for the trouble but something still seems to be going wrong with the CLA. Are you signing as an individual or through a corporate CLA?

**Comment by BartHertog** [comment]
@acozzette It is a corporate CLA.

**Comment by BartHertog** [comment]
@googlebot I signed it!

**Comment by BartHertog** [comment]
@acozzette The CLA I have signed a gain with the correct title. I have received confirmation in my email. What are the next steps?

**Comment by acozzette** [comment]
Thanks, @BartHertog.

**Pull request merged**
