### PR TITLE
Optimized layout_mark() for Ruby

### PR DESCRIPTION
**Pull request by haberman**

### CODE REVIEW

**Comment by samphippen** [comment]
confirm this takes a representative ads benchmark from 18s to 11s.

**Comment by haberman** [comment]
I think this is ready to merge. All of the Ruby tests are passing.

**Comment by haberman** [comment]
Oh no, this failure is back, in the Linux Ruby 2.3 test:

```
Failure: test_concurrent_decoding(BasicTest::MessageContainerTest)
/tmp/protobuf/protobuf/ruby/tests/basic.rb:245:in `block (3 levels) in test_concurrent_decoding'
     242:       thds = 2.times.map do
     243:         Thread.new do
     244:           100000.times do
  => 245:             assert_equal o, Outer.decode(raw)
     246:           end
     247:         end
     248:       end
/tmp/protobuf/protobuf/ruby/tests/basic.rb:244:in `times'
/tmp/protobuf/protobuf/ruby/tests/basic.rb:244:in `block (2 levels) in test_concurrent_decoding'
```

But it's not being caused by this PR, so it shouldn't block merging this PR.

**Comment by haberman** [comment]
The failure is unrelated to this PR (and is fixed by https://github.com/protocolbuffers/protobuf/pull/6541). I'm merging this now.

**Pull request merged**
