### PR TITLE
Auto capitalize enums name in Ruby (#10454)

### PR DESCRIPTION
**Pull request by tisonkun**
This picks #10454 to branch-2.11. Refer to #1965.

cc @JasonLunn @mkruskal-google

### CODE REVIEW

**Comment by tisonkun** [comment]
ping @JasonLunn @mkruskal-google could you help with triggering the tests?

**Review by deannagarcia — APPROVED** [review]

**Comment by deannagarcia** [comment]
Thanks for upstreaming this! We don't have a planned date for the next release but should be within the next few weeks.

**Comment by tisonkun** [comment]
@deannagarcia @mkruskal-google emmm...IIRC I open this PR against 21.x but it's now merged into master (and I don't find the commit on master). What should I do now? @deannagarcia @mkruskal-google could you help with cherrypicking this patch?

**Comment by tisonkun** [comment]
I create a new PR. This time I confirm that it's against 21.x:

image

If you'd like to proceed it, be careful before you click the merge button - I don't know what happened here :(

**Pull request merged**
