### PR TITLE
Fix .NET Native AOT warnings in Protobuf reflection

### PR DESCRIPTION
**Pull request by JamesNK**
The fixes from https://github.com/protocolbuffers/protobuf/pull/10978. This PR can be merged without updating the SDK. Will allow people to use Protobuf + AOT sooner rather than later.

When the repo is updated to .NET 7 or .NET 8, the original PR can be rebased on latest to add AOT analysis and provide some AOT smoke tests.

cc @jskeet

### CODE REVIEW

**Comment by jskeet** [comment]
Thanks. I'm on vacation for the weekend but will look on Monday.

**Review by jskeet — APPROVED** [review]
Thanks for this! Will run it through Kokoro and get it merged. Hopefully we can get the SDK update and tests in reasonably soon afterwards.

**Comment by jskeet** [comment]
(The actual merge will be slightly delayed as we're sorting out internal mirroring for the C# codebase; I'll talk with the team about whether we should force-merge this one.)

**Review by deannagarcia — APPROVED** [review]

**Comment by JamesNK** [comment]
Rebased.

**Review by jskeet — APPROVED** [review]

**Comment by JamesNK** [comment]
Nice!

@jskeet Are you able to give a rough estimate of when this will be available in a release?

cc @jtattermusch

**Comment by jskeet** [comment]
@JamesNK: I'm expecting it "pretty soon" if everything goes smoothly. I'd rather not be more precise than that and put the Protobuf team in a corner :)

**Comment by jtattermusch** [comment]
@JamesNK 
I might be missing context, but AFAICT, protobuf has only done releases from the 21.x branch for the past several months and I don't know of a plan to create a new release branch anytime soon (that might be just my ignorance). Since the timeline for the next release branch is unclear, I'd say it's a safer bet to proactively create a PR that backports to 21.x branch, so that the fix appears in the next patch release of Google.Protobuf nuget (which is going to 3.21.x).
Especially since you mentioned that this change is somewhat time sensitive.

**Comment by jskeet** [comment]
> I'd say it's a safer bet to proactively create a PR that backports to 21.x branch, so that the fix appears in the next patch release of Google.Protobuf nuget (which is going to 3.21.x).

Please hold off on this for now - sorry about the mixed messages; too many teams involved!

**Pull request closed without merging**
