### PR TITLE
Backport #6759 and disable extension code gen for C#

### LINKED ISSUE #6749: 3.9+ C# lack of backward compatibility with extensions
Version: v3.10
Language: C#
OS: Windows/Linux
Runtime: .NET Core 2.1

**What did you do?**
1. Generate and compile a proto **which has extensions in it** to C# using version 3.8 or earlier, or use Grpc.Tools (which is submoduled to 3.x of this repo).
2. Use the new DLL in a C# project which uses a reference to 3.9 or later of Google.Protobuf. Note again, this can actually be done from the *same* project if you use Grpc.Tools to compile, and Google.Protobuf v3.9+ as a reference.
3. Note exception when running and any code that will trigger the static initializer on the generated class(es).

**What did you expect to see**
No exception

**What did you see instead?**
A static initializer error reading the descriptor.
```
Index was outside the bounds of the array.
   at Google.Protobuf.Reflection.ExtensionCollection.<>c__DisplayClass2_0.<.ctor>b__0(FieldDescriptorProto extension, Int32 i) in T:\src\github\protobuf\csharp\src\Google.Protobuf\Reflection\ExtensionCollection.cs:line 51
   at Google.Protobuf.Reflection.DescriptorUtil.ConvertAndMakeReadOnly[TInput,TOutput](IList`1 input, IndexedConverter`2 converter) in T:\src\github\protobuf\csharp\src\Google.Protobuf\Reflection\DescriptorUtil.cs:line 59
   at Google.Protobuf.Reflection.ExtensionCollection..ctor(FileDescriptor file, Extension[] extensions) in T:\src\github\protobuf\csharp\src\Google.Protobuf\Reflection\ExtensionCollection.cs:line 49
   at Google.Protobuf.Reflection.FileDescriptor..ctor(ByteString descriptorData, FileDescriptorProto proto, IEnumerable`1 dependencies, DescriptorPool pool, Boolean allowUnknownDependencies, GeneratedClrTypeInfo generatedCodeInfo) in T:\src\github\protobuf\csharp\src\Google.Protobuf\Reflection\FileDescriptor.cs:line 87
   at Google.Protobuf.Reflection.FileDescriptor.BuildFrom(ByteString descriptorData, FileDescriptorProto proto, FileDescriptor[] dependencies, Boolean allowUnknownDependencies, GeneratedClrTypeInfo generatedCodeInfo) in T:\src\github\protobuf\csharp\src\Google.Protobuf\Reflection\FileDescriptor.cs:line 344
   at Google.Protobuf.Reflection.FileDescriptor.FromGeneratedCode(Byte[] descriptorData, FileDescriptor[] dependencies, GeneratedClrTypeInfo generatedCodeInfo) in T:\src\github\protobuf\csharp\src\Google.Protobuf\Reflection\FileDescriptor.cs:line 385
   at redacted
```

**Anything else we should know about your project / environment**
This comes from here:
https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/Reflection/ExtensionCollection.cs#L56 where it looks like **closure over `extensions` makes the poor assumption that `message.Proto.Extension` will have the same length**.

v3.9 added extensions into the generated code as seen [here](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/csharp/csharp_reflection_class.cc#L211).  However older code generated without this GeneratedClrType constructor overload fails at the static initializer reading the Descriptor as it isn't aware of the extensions.

This is also very related to https://github.com/protocolbuffers/protobuf/issues/5957 which seems to indicate that this type of compatibility will be marked by an API version, referenced [here](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.props#L7).

Also opened https://github.com/grpc/grpc/issues/20557 in the Grpc project to start a discussion about updating the version of protoc submoduled there.

/cc: @ObsidianMinor @jtattermusch

### PR DESCRIPTION
**Pull request by ObsidianMinor**
This fixes #6749, #6510, and #6509

(Backports #6759 into 3.10.x branch).

### CODE REVIEW

**Comment by ObsidianMinor** [comment]
I hope I did this patch right. @jtattermusch

**Comment by ObsidianMinor** [comment]
Yeah, I forgot this requires removing a lot more code to make custom options work. Try running kokoro again.

**Comment by jtattermusch** [comment]
@rafi-kamal  can we push a new patch release after merging this?

**Comment by rafi-kamal** [comment]
Sure, will do.

**Comment by rafi-kamal** [comment]
@jtattermusch I tried doing a release today, but it's blocked on https://groups.google.com/a/google.com/forum/#!topic/maven-users/XahhvcPnwfw due to a protoc error. Does C# protobuf depend on protoc? If not, then I can do a release only for C# without releasing protoc.

**Comment by ObsidianMinor** [comment]
Part of the patch disables certain C# code-gen so for it to be completely effective protoc should be included.

**Comment by rafi-kamal** [comment]
Release 3.10.1 to Nuget. I'll be OOO for a week from this afternoon so please reach out to the protobuf team if there is any problem.

On a side note, does anyone have instructions for rolling back released Nuget packages so that I can link it to our release docs?

**Comment by jtattermusch** [comment]
The new nuget is here: https://www.nuget.org/packages/Google.Protobuf/3.10.1

Ad "rolling back" packages: there is no such thing with nuget.org. You can only mark packages as "unlisted" in nuget.org UI (= they will be still there for those who reference that version in their project, but they won't show up in search results).  To unlist you just log in to www.nuget.org and mark specific package version as "unlisted".

**Comment by jtattermusch** [comment]
@ObsidianMinor  because this PR also has codegen changes, it sounds like we'll need to also pull the changes into Grpc.Tools nuget (which also bundles `protoc` binary) for the fix to be really effective?

**Pull request merged**
