### PR TITLE
Cherry-pick fix for compatibility with Python 3.7

### PR DESCRIPTION
**Pull request by acozzette**
This cherry-picks the fix from PR #4862 so that we can include it in a 3.6.1.2 patch release.

### CODE REVIEW

**Comment by acozzette** [comment]
The CLA is OK because it was already verified when this fix was merged as part of PR #4862.

**Comment by TeBoring** [comment]
Why #4940 still fail?

**Comment by acozzette** [comment]
I'm not sure about #4940 but it looks like those tests are probably failing because of some kind of issue with the test setup and not necessarily a real problem with Python 3.7. The TensorFlow team requested this cherry-pick because they have users who want to upgrade to Python 3.7.

**Comment by TeBoring** [comment]
To build python 3.7, you probably also needs #5406. Otherwise, the built wheel cannot be run on latest mac (usually python 3.7 is on the newest mac)

**Pull request merged**
