### PR TITLE
Update GSON version to 3.8.5

### LINKED ISSUE #3531: Update protobuf-java-util gson dep from v2.7 to v2.8.1
protobuf-java-util isn't using the latest gson. I had to add a gradle exclude rule. It'd be nice to update to the latest stable version.

### PR DESCRIPTION
**Pull request by haon4**
Fixes #3531

### CODE REVIEW

**Comment by TeBoring** [comment]
In #3531, there seems to be some concern about compatibility of gson.

**Comment by haon4** [comment]
Sorry I missed your last comment. We upgraded the Gauva library in one of our previous releases and there wasn't an issue. I don't think GSON would be that different, right?

**Comment by henryju** [comment]
This issue is marked as closed and the changelog indicates it was released in protobuf 3.9.0. But the pom on Maven central is still referencing gson 2.7:
http://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.9.1/protobuf-java-util-3.9.1.pom

**Comment by henryju** [comment]
And BTW the changelog and this PR title are wrong, the new version is 2.8.5, not 3.8.5.

**Pull request merged**
