### PR TITLE
Write generated source files to the build tree, not the source tree.

### PR DESCRIPTION
**Pull request by iskunk**
My org, as part of its reproducible-build hygiene, builds projects with the source trees in read-only mode. I approached the protobuf build in the same way, but encountered this error (among others):
```
[ 30%] Built target statusor
[ 34%] Built target libprotobuf-lite
[ 45%] Built target libprotobuf
Consolidate compiler generated dependencies of target libprotoc
[ 62%] Built target libprotoc
Consolidate compiler generated dependencies of target protoc
[ 62%] Built target protoc
Consolidate compiler generated dependencies of target scoped_mock_log
[ 62%] Built target scoped_mock_log
[ 62%] Generating /home/src/protobuf/src/google/protobuf/util/message_differencer_unittest_proto3.pb.h, /home/src/protobuf/src/google/protobuf/util/message_differencer_unittest_proto3.pb.cc
/home/src/protobuf/src/google/protobuf/util/message_differencer_unittest_proto3.pb.cc: Read-only file system
make[2]: *** [CMakeFiles/libtest_common.dir/build.make:387: /home/src/protobuf/src/google/protobuf/util/message_differencer_unittest_proto3.pb.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:1194: CMakeFiles/libtest_common.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
(`/home/src` is a read-only mount)

Generated source files are effectively build artifacts, and should be written to the build tree, not the source tree. This PR accordingly enables a successful build and test run (lite, full, and conformance) with read-only sources.

(Beyond this, I would add that CMake usually does not need source file paths to be qualified with `CMAKE_SOURCE_DIR` or `CMAKE_BINARY_DIR`; in most cases it knows to look in both locations, favoring the latter if a file is in both. The CMake code could be simplified by relying on this behavior.)

### CODE REVIEW

**Review by acozzette — APPROVED** [review]

**Comment by iskunk** [comment]
What is the status of this PR? Are there any further concerns with the changes?

Given that a couple releases have already gone out, I'd like to get this resolved.

**Comment by hlopko** [comment]
Hi, seems there are built time problems:

```
ERROR: /workspace/third_party/utf8_range/fuzz/BUILD.bazel:3:13: every rule of type fuzzing_corpus implicitly depends upon the target '@rules_fuzzing//fuzzing/tools:make_corpus_dir', but this target could not be found because of: error loading package '@rules_fuzzing//fuzzing/tools': Unable to find package for @fuzzing_py_deps//:requirements.bzl: The repository '@fuzzing_py_deps' could not be resolved: Repository '@fuzzing_py_deps' is not defined.
Documentation for implicit attribute _corpus_tool of rules of type fuzzing_corpus:
The tool script to copy and rename the corpus.
ERROR: /workspace/third_party/utf8_range/fuzz/BUILD.bazel:3:13: every rule of type fuzzing_dictionary implicitly depends upon the target '@rules_fuzzing//fuzzing/tools:validate_dict', but this target could not be found because of: error loading package '@rules_fuzzing//fuzzing/tools': Unable to find package for @fuzzing_py_deps//:requirements.bzl: The repository '@fuzzing_py_deps' could not be resolved: Repository '@fuzzing_py_deps' is not defined.
Documentation for implicit attribute _validation_tool of rules of type fuzzing_dictionary:
The tool script to validate and merge the dictionaries.
Analyzing: 330 targets (149 packages loaded, 1626 targets configured)
Analyzing: 330 targets (161 packages loaded, 1763 targets configured)
Analyzing: 330 targets (169 packages loaded, 2238 targets configured)
ERROR: /workspace/third_party/utf8_range/fuzz/BUILD.bazel:3:13: no such target '//:utf8_validity': target 'utf8_validity' not declared in package '' defined by /workspace/BUILD.bazel (Tip: use `query "//:*"` to see all the targets in that package) and referenced by '//third_party/utf8_range/fuzz:utf8_validity_fuzzer_raw_'
```

Could you take a look please?

**Comment by hlopko** [comment]
Hmm those seem unrelated to your PR, let me take a deeper look.

**Review by acozzette — APPROVED** [review]

**Review by acozzette — APPROVED** [review]

**Comment by iskunk** [comment]
Thanks @acozzette! Glad this passed muster.

**Pull request closed without merging**
