### PR TITLE
Fixed the use of c++ keywords within namespace names

### PR DESCRIPTION
**Pull request by Ilukatsk**

### CODE REVIEW

**Review by fowles — APPROVED** [review]

**Comment by Ilukatsk** [comment]
Do I need to do something to fix the issue with failed PHP test before sbenzaquen will approve the merge or should I just wait?

**Comment by zhangskz** [comment]
Thanks for the ping! We temporarily disabled the failing PHP test which was blocking the PR from going through. Rebasing would unstick this, but we've already imported your PR to be merged. No action is needed on your part at this time -- but please give us another ping if you don't see this go through in the next day or so.

**Comment by Ilukatsk** [comment]
Good afternoon. Sorry for bothering, but is it known, when the commit will be included in the release version?

**Comment by zhangskz** [comment]
This should be picked up in our next quarterly 27.x minor release, which we should start cutting RC's for ~next week!

**Comment by Ilukatsk** [comment]
Great! Thanks for the info

**Pull request closed without merging**
