### PR TITLE
[ObjC] Use os_unfair_lock instead of dispatch_semaphore_t.

### PR DESCRIPTION
**Pull request by thomasvl**
The minOS version is high enough it can be used, and it avoids the long standing issue for priority inversion dependent on what callers did with threading/queues.

### CODE REVIEW

**Review by dmaclach — APPROVED** [review]
Fixed up some grammar/spelling. Let me know what you think.

**Comment by thomasvl** [comment]
> Fixed up some grammar/spelling. Let me know what you think.

lg, tx.

**Comment by dnkoutso** [comment]
👋 @thomasvl @dmaclach sorry for pinging you in the PR, this has not been released yet is that correct?

**Comment by thomasvl** [comment]
Sorry, not sure, I'm now really involved in the release process.  I believe there is a new release expect at the start of this year, so at a minimum it will hopefully be in that.

**Comment by dnkoutso** [comment]
Thank you @thomasvl !

**Pull request merged**
