### PR TITLE
[python-runtime] Add MethodDescriptor.CopyToProto()

### PR DESCRIPTION
**Pull request by alkasm**
Fixes: https://github.com/protocolbuffers/protobuf/issues/8326

### CODE REVIEW

**Comment by alkasm** [comment]
Bumping this, would like to get it merged in!

**Comment by fowles** [comment]
Please address the Mergable failures about release note and language label

**Comment by alkasm** [comment]
@fowles thanks for taking a look. AFAIK I cannot edit the labels.

**Comment by fowles** [comment]
Sorry, didn't realize that you had to be in the official club to edit labels.  I will do a final review on Monday.

**Comment by fowles** [comment]
Overall this change looks good.  Can you add a test in google/protobuf/internal/descriptor_test.py?

**Comment by alkasm** [comment]
Oh, excellent---it's already there! I believe can just remove the decorator to skip checking on the python implementation.

**Comment by fowles** [comment]
Thanks!  I just kicked off the CI system to test this and will try to merge this later today or early tomorrow.

**Pull request merged**
