### PR TITLE
JsonFormat - allow one-liners

### PR DESCRIPTION
**Pull request by michaldo**
With proposed change simpler code is possible, for example
```
FooMessage fooMessage = JsonFormat.parser().merge(json, FooMessage.newBuilder()).build();

### CODE REVIEW

**Comment by midovlvn** [comment]
I see now I shoud add some generics to achieve my goal. Returning just `Message.Builder` needs downcasting. 
```
FooMessage fooMessage = (FooMessage) JsonFormat.parser().merge(json, FooMessage.newBuilder()).build();
```

I will continue PR development

**Comment by googleberg** [comment]
@michaldo @midovlvn Be sure to sign the CLA so we can look at your PR when it is ready.

**Comment by michaldo** [comment]
> @michaldo @midovlvn Be sure to sign the CLA so we can look at your PR when it is ready.

cla/google check pass, I think CLA is signed well

**Comment by michaldo** [comment]
@googleberg @shaod2 please tell me clearly if you expect any action from my side.

**Comment by midovlvn** [comment]
This PR is active.

**Comment by michaldo** [comment]
This PR is active.

**Comment by michaldo** [comment]
This PR is active.

**Comment by michaldo** [comment]
This PR is active.

**Review by googleberg — APPROVED** [review]

**Review by googleberg — APPROVED** [review]

**Comment by googleberg** [comment]
@michaldo  I've tried to rerun the tests a couple of times. I suspect that you need to rebase and we can try again.

**Comment by michaldo** [comment]
> @michaldo I've tried to rerun the tests a couple of times. I suspect that you need to rebase and we can try again.

I just synchronized my branch with main

**Comment by googleberg** [comment]
Oh shoot. @midovlvn it looks like you still haven't signed the CLA. We can't go any further until that happens.

**Comment by michaldo** [comment]
@googleberg I see one merge commit is signed by my corporate git account by mistake. I prefer do not sign any licence with my corporate account.
Maybe I will close this PR and I open new one, only with commits signed by my private git account with signed CLA?

**Comment by midovlvn** [comment]
Finally I made force-push on my branch and I removed commits from my corporate account

**Comment by googleberg** [comment]
@michaldo I'm so sorry to realize this late. I can't merge this change because it changes the return type of public methods. That isn't ABI compatible -- it qualifies as a mildly breaking change and we will get complaints. I can put it on the list of breaking changes for PBJ 5.x in 2026 Q1.

**Comment by michaldo** [comment]
> @michaldo I'm so sorry to realize this late. I can't merge this change because it changes the return type of public methods. That isn't ABI compatible -- it qualifies as a mildly breaking change and we will get complaints. I can put it on the list of breaking changes for PBJ 5.x in 2026 Q1.

Go ahead!

**Pull request closed without merging**
