### PR TITLE
Retain existing array in RepeatedField.Clear

### LINKED ISSUE #7828: [C#] Enable pooling of messages with large RepeatedFields
**What language does this apply to?**
C# proto3

**Describe the problem you are trying to solve.**
Sending multiple messages, each containing a large `RepeatedField` (all of the same size), without allocating a new backing array for each `RepeatedField`. Effectively, I'd like to be able to pool `RepeatedFields` for reuse.

**Describe the solution you'd like**
One possible solution could be to provide a method similar to `Clear`, which keeps the backing array and only resets the `count` field (see [here](https://github.com/protocolbuffers/protobuf/blob/214c77e1b76e63e512bd675d1c300c80438642b6/csharp/src/Google.Protobuf/Collections/RepeatedField.cs#L344)).

### PR DESCRIPTION
**Pull request by jskeet**
Fixes #7828.

(Also tweaks the comment for Capacity.)

### CODE REVIEW

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by jskeet** [comment]
@fowles: Please could you approve and merge (assuming this does indeed seem reasonable to you)?

**Review by fowles — APPROVED** [review]

**Comment by CodeBlanch** [comment]
@jskeet Hey I don't see this change in latest NuGet release tag ([3.21.7](https://github.com/protocolbuffers/protobuf/blob/54489e95e01882407f356f83c9074415e561db00/csharp/src/Google.Protobuf/Collections/RepeatedField.cs#L344-L348)) are you able to provide any hint on when it might drop?

**Comment by jskeet** [comment]
@CodeBlanch: I would expect it to be in 3.22.0; I don't have a timeframe for that.

**Pull request merged**
