### PR TITLE
Backport Bazel-incompatible fixes to 3.9.x (orginal: #6432)

### PR DESCRIPTION
**Pull request by Yannic**
@acozzette Thank you for your reviews! Can we cherry-pick this onto 3.9.x and possibly get a new release in the next 2-3 weeks before Bazel 0.29.0 drops?

### CODE REVIEW

**Comment by acozzette** [comment]
Thanks, @Yannic. I am guessing we probably won't do another 3.9.x release because we usually don't do patch releases unless there's a particularly important bug fix. But it can't hurt to cherrypick this just in case. Actually now that I think of it, we could potentially do a Bazel-only 3.9.1 release. The releases are a lot of work when we have to publish artifacts for every language, but if it's just for Bazel then that is easy.

**Comment by Yannic** [comment]
@acozzette I see. Maybe let's wait then to see if there are other changes that justify a patch release. It's always possible to cut a new release if lots of people start complaining about a broken build.

**Comment by jmillikin-stripe** [comment]
I think there was a typo in this PR. `build_file = "@//:six.BUILD",` is referencing a file in the top-level workspace -- you probably meant `build_file = "@com_google_protobuf//:six.BUILD",` instead.

**Comment by Yannic** [comment]
Yes, your right. Voting for #6391 to fix it. @anandolee @acozzette Can you help to get the fix merged?

**Pull request merged**
