### PR TITLE
Fix PyUnknownFields memory leak

### LINKED ISSUE #7301: [Python] PyUnknownFields Memory leak
**What version of protobuf and what language are you using?**
Version: v3.5.1
Language: Python

**What operating system (Linux, Windows, ...) and version?**
System: Linux / Mac

**What runtime / compiler are you using (e.g., python version or gcc version)**
PythonVersion: 3.7.4
ProtobufPackageVersion: 3.11.3

**What did you do?**
```proto
syntax = "proto3";

message Msg
{
  uint32 u32_id = 1;
}
```

```python
import os, psutil, gc
import tracemalloc

from a_pb2 import Msg

def get_mem():
    rss = psutil.Process(os.getpid()).memory_info().rss
    print(rss / 1024 / 1024)

def get_unknown_field():
    msg = Msg()
    unknown_fields = msg.UnknownFields()  # it raise memory leak
    #  print(unknown_fields)

tracemalloc.start()

get_mem()

for i in range(10000000):
    get_unknown_field()

gc.collect()
get_mem()

snapshot = tracemalloc.take_snapshot()
top_stats = snapshot.statistics('lineno')
for stat in top_stats:
    print(stat)
```

**What did you expect to see**
Process's memory will be freed.

**What did you see instead?**
Python Output:
image

Output with tracemalloc:
image

It looks like the memory has not been freed.  May be it's a bug?

### PR DESCRIPTION
**Pull request by agrenott**
Properly release internal data structure on deallocation.
Fix #7301

### CODE REVIEW

**Comment by agrenott** [comment]
@googlebot I signed it!

**Comment by agrenott** [comment]
I disabled the new memory leak unit test for python versions <3.4 (as tracemalloc wasn't available back then).

**Comment by agrenott** [comment]
Hi,
Is anything on my side missing to get this PR reviewed/integrated?
This leak's quite a show-stopper on our side.
Thx

**Comment by agrenott** [comment]
Hi,
Any idea when this PR could get merged (or what's missing)?
Thx.

**Review by dlj-NaN — APPROVED** [review]

**Comment by dlj-NaN** [comment]
Thanks, and sorry for the delay.

**Comment by agrenott** [comment]
Hi,
Thanks for the merge.
Is there a way to get it merged into the on-going 3.14.x branch? If so what's the process?

**Comment by acozzette** [comment]
@agrenott Thanks for flagging this, I created #8032 to cherry-pick this fix into the 3.14.x branch.

**Pull request merged**
