### PR TITLE
Add overrides in C++ code.

### PR DESCRIPTION
**Pull request by arunov**

### CODE REVIEW

**Comment by arunov** [comment]
In json_objectwriter.h, RenderNullAsEmpty is better left virtual since we could potentially have a class derived from JsonObjectWriter.

**Comment by acozzette** [comment]
@arunov Thanks for the pull request!

**Comment by arunov** [comment]
@acozzette Thank you for reviewing and accepting it!

**Comment by mergeconflict** [comment]
I think this PR got unintentionally clobbered by the github export process somehow (see https://github.com/protocolbuffers/protobuf/commit/624a40a387e1b2da4c6bbde44ad3d0a5efb9879b#diff-37bf05f81266114e58575cf185d7dbfc) @TeBoring

**Pull request merged**
