### PR TITLE
WIP: Remove _CheckCalledFromGeneratedFile

### PR DESCRIPTION
**Pull request by thisch**
and related functions.

Closes: #4794

### CODE REVIEW

**Comment by thisch** [comment]
Does anyone know why the setter functions that are called when attributes in the _pb2 files are set, only return the return value of CheckCalledFromGeneratedFile() and not change the pyobject (see e.g. https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/pyext/descriptor.cc#L572)? 

The reason why I'm asking is that removing those setter functions causes problems in the generated _pb2.py files:

```
  File "/Users/travis/build/thisch/protobuf/python/google/protobuf/descriptor_pb2.py", line 1752, in <module>
    _DESCRIPTORPROTO_EXTENSIONRANGE.containing_type = _DESCRIPTORPROTO
```

**Comment by anandolee** [comment]
Because you have removed the (setter)SetContainingType. Can just return 0 in SetContainingType()

**Comment by thisch** [comment]
Maybe it makes sense that protoc generates code, which checks if the cpp-"backend" is used or not (using .e.g. `google.protobuf.descriptor._USE_C_DESCRIPTORS`).

**Comment by thisch** [comment]
I see two options for moving forward with this PR.

1) Make the protoc generated python code compatible with backend agnostic.
2) Introduce a new protoc plugin that outputs python code that can only be used with the cpp backend.

 (Note that I would prefer if somebody else that is more familiar with the protoc codebase could do this)

WDYT?

**Comment by anandolee** [comment]
In my other work of python descriptor pool, I am also thinking of adding checks if the cpp backend is used. However for compatibility issue it is still unable to remove those APIs: old generated code should work with new runtime. 

I may add the checks to improve cpp performance and make it possible to remove those APIs in future(might a few years later). But for now, we definitely can't break compatibility

**Comment by thisch** [comment]
Do you really think that we have to support the code generated by an older version of protoc? If yes, we can aim for changing the output format with the next major version of protobuf. WDYT?

What are the plans for the cpp backend? Will it replace the python backend in the future?

> I may add the checks to improve cpp performance

I don't understand what you mean by checks here. How can checks improve the performance?

**Comment by anandolee** [comment]
Will close it for clean up. Feel free to reopen if still need

**Pull request closed without merging**
