### PR TITLE
export EnumName for c++

### PR DESCRIPTION
**Pull request by zwkno1**

### CODE REVIEW

**Comment by zhangskz** [comment]
Is this for the same issue as https://github.com/protocolbuffers/protobuf/issues/12932?

**Review by zhangskz — APPROVED** [review]

**Comment by zwkno1** [comment]
> Is this for the same issue as #12932?

mybe not. i was writing a protoc plugin  and want to use this function.

**Comment by zhangskz** [comment]
Apologies, looks like this got stuck behind a failing test after approval and the logs don't seem to be present anymore (not sure if legitimate failure or a flake).
 
I've triggered a rerun but I suspect this change will need to be rebased or manually imported.

**Comment by zhangskz** [comment]
You should be able to use ClassName(const EnumDescriptor* enum_descriptor) instead for enums: https://github.com/protocolbuffers/protobuf/blob/e26cb4864db312fce543f2a58b7822f090428124/src/google/protobuf/compiler/cpp/helpers.cc#L412

We don't actually have a separate EnumName function to expose here.

**Pull request closed without merging**
