### PR TITLE
feat: add protons extension

### PR DESCRIPTION
**Pull request by achingbrain**
Adds an extension id to the registry for use by the [protons](https://www.npmjs.com/package/protons) protobuf encoder/decoder.

### CODE REVIEW

**Comment by achingbrain** [comment]
@acozzette @fowles sorry to ping you directly but it looks like you've recently merged PRs that add extension number reservations - what needs to happen for this to be merged?

**Review by acozzette — APPROVED** [review]

**Comment by achingbrain** [comment]
@acozzette thanks for approving!  It looks like there's an internal check that failed so it wasn't merged?  I can't access the "Details" link, it must be some internal Google thing?

**Comment by acozzette** [comment]
@achingbrain Sorry for the delay, I was able to get it unstuck so that it has now been submitted.

**Comment by achingbrain** [comment]
That's great, thanks so much

**Pull request closed without merging**
