### PR TITLE
[C#] Optimize memory allocations when parsing numbers in .NET5 or greater

### PR DESCRIPTION
**Pull request by TrayanZapryanov**
Do not use StringBuilder when loading and parsing numbers by using char buffer.
If target is NET5 or greater stackalloc can be used, but due to compatibility reasons we cannot use some Span<> methods.

### CODE REVIEW

**Comment by jskeet** [comment]
Again, I'm not going to have time to get to this any time soon.

**Comment by jskeet** [comment]
This will conflict with #15794. Do you want me to go ahead getting a final review for that and getting that merged, or is this your preferred approach now?

**Comment by TrayanZapryanov** [comment]
> Again, I'm not going to have time to get to this any time soon.

No worries. Do it once you have time.

**Comment by TrayanZapryanov** [comment]
> This will conflict with #15794. Do you want me to go ahead getting a final review for that and getting that merged, or is this your preferred approach now?

Please review and merge the other one first. This one will be adapted after that.

**Comment by TrayanZapryanov** [comment]
Same benchmark as [here](https://github.com/protocolbuffers/protobuf/pull/15795#issuecomment-1980222331)

Main
// * Summary *

BenchmarkDotNet v0.13.12, Windows 11 (10.0.22631.3235/23H2/2023Update/SunValley3)
11th Gen Intel Core i9-11900K 3.50GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.200
  [Host]     : .NET 8.0.2 (8.0.224.6711), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  DefaultJob : .NET 8.0.2 (8.0.224.6711), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

Job=DefaultJob  Error=3.84 ns  StdDev=3.21 ns

| Method | Mean         | Allocated |
|------- |-------------:|----------:|
| Small  |     281.1 ns |   1.01 KB |
| Big    | 256,221.4 ns |  642.7 KB |

PR
Optimize number
| Method | Mean         | Allocated |
|------- |-------------:|----------:|
| Small  |     264.0 ns |     936 B |
| Big    | 260,213.7 ns |  564016 B |

**Comment by jskeet** [comment]
Please could update this in light of the current HEAD? I can then try to take a look next week.

**Pull request closed without merging**
