### PR TITLE
Apply Obsolete attribute to deprecated enums and enum values in C# generated code

### LINKED ISSUE #10513: deprecate for enum value not adding obsolete to generated c# models
**What version of protobuf and what language are you using?**
Version: v3.21.5
Language: C#
OS: Windows 10

**What did you do?**
I have a protobuf schema, which has an enum, some of the enum values are no longer required and I want to deprecate them, I added deprecate = true with the values but it doesn't add the [Obsolete] attribute in the generated c# model
here is the code example

`enum Months{`
`	JANUARY = 0 [deprecated = true];`
`	FEBRUARY = 1 [deprecated = true];`
`	MARCH = 2 [deprecated = true];`
`	APRIL = 3 [deprecated = true];`
`	MAY = 4;`
`	JUNE = 5 [deprecated = true];`
`	JULY = 6 [deprecated = true];`
`	AUGUST = 7;`
`	SEPTEMBER = 8 [deprecated = true];`
`       OCTOBER = 9;`
`       NOVEMBER = 10;`
`       DECEMBER = 11;`
`}`

### PR DESCRIPTION
**Pull request by jskeet**
Fixes #10513

### CODE REVIEW

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Review by fowles — APPROVED** [review]

**Comment by jskeet** [comment]
I believe the Kokoro errors are the ones that would be fixed by https://github.com/protocolbuffers/protobuf/pull/10523 - @fowles, are you happy to merge?

**Comment by mkruskal-google** [comment]
Yea these should be unrelated and fixed now

**Comment by jskeet** [comment]
Rebased - will see if it goes green...

**Comment by jskeet** [comment]
Kokoro is green :) @fowles, please merge if you're happy.

**Pull request merged**
