### PR TITLE
Add example in ruby

### PR DESCRIPTION
**Pull request by mlitwiniuk**
examples directory was missing an example in ruby, this PR aims to fix this.

### CODE REVIEW

**Comment by mkruskal-google** [comment]
This Makefile is actually partially deprecated, and not currently tested by our CI.  We plan to migrate this to Bazel in the future, and the current Bazel setup is the only thing we test in our CI.  That being said, this doesn't really make the situation worse so it seems reasonable

**Comment by mkruskal-google** [comment]
Could you rebase this PR to main?  You caught us in the middle of a CI migration

**Comment by mlitwiniuk** [comment]
Hi @mkruskal-google no worries, rebase done.

**Comment by mkruskal-google** [comment]
Sorry, can you rebase one more time?  This LGTM but the one test failure is preventing automated import

**Comment by mlitwiniuk** [comment]
@mkruskal-google no worries, here you go.

**Review by mkruskal-google — APPROVED** [review]

**Pull request closed without merging**
