### PR TITLE
Down integrate to Github

### PR DESCRIPTION
**Pull request by haon4**

### CODE REVIEW

**Comment by BSBandme** [comment]
Seems I didn't added to the internal log update CL reviewer...
And would you please resolve the conflicts? Seems not too hard to fix.

**Comment by haon4** [comment]
Sent out the integrate log CL. Seems like the my automated tool needs more work...

Merged the conflicts.

**Comment by BSBandme** [comment]
Maybe adding a notes after merging into local git is fine since you just removed automatic sending CL. 

And what is protobuf-sync? I just assumed it won't have any CLA issues.

**Comment by haon4** [comment]
protobuf-sync is a role account that I am trying to setup to do this automatically. It is not quite working yet, but it is just a bot.

**Comment by BSBandme** [comment]
I think the ruby failures are about #5840, which are unrelated to this PR. I think it's good to go

**Comment by haon4** [comment]
I see. Thanks for pointing that out!

**Pull request merged**
