### PR TITLE
Update third_party.md with Philips Rpc implementation

### PR DESCRIPTION
**Pull request by oguzcanoguz**

### CODE REVIEW

**Review by acozzette — COMMENTED** [review]
Are you sure this is the right link? I'm getting a "page not found" error.

**Comment by oguzcanoguz** [comment]
> Are you sure this is the right link? I'm getting a "page not found" error.

@acozzette You are right, fixed the link.

**Review by acozzette — APPROVED** [review]

**Comment by acozzette** [comment]
@oguzcanoguz Could you rebase your branch on main and push it again? I think that will fix the test failures.

**Comment by oguzcanoguz** [comment]
@acozzette Updated with main

**Review by acozzette — APPROVED** [review]

**Comment by oguzcanoguz** [comment]
@acozzette Any ideas why feedback/copybara check is failing?

**Review by acozzette — APPROVED** [review]

**Pull request closed without merging**
