### PR TITLE
Revert "delete all duplicate empty blanks"

### PR DESCRIPTION
**Pull request by TeBoring**
Reverts protocolbuffers/protobuf#5758

### CODE REVIEW

**Comment by BSBandme** [comment]
The fix should have been submitted in #5762.
I think current broken in mac is because of Kokoro updates and m4 isn't installed by default. 

I think we'd add m4 in prepare_build_macos_rc for fixing.

**Comment by TeBoring** [comment]
Ah, I see. Could you help send a fix for that?

**Comment by BSBandme** [comment]
I'll give a try, but may take some time as I'm not very familiar with mac's m4 dependency and how we can install it by `brew install`.

**Comment by TeBoring** [comment]
Maybe check with kokoro team?

**Pull request closed without merging**
