### PR TITLE
Fix NPE during encoding and add regression test for issue 9507.

### LINKED ISSUE #9507: Calling `inspect` on a proto instance causes a `NullPointerException` on subsequent `to_proto`
**What version of protobuf and what language are you using?**
Version: v3.19.4
Language: JRuby

**What operating system (Linux, Windows, ...) and version?**

Linux, official JRuby 9.3.3.0 docker image (`jruby:9.3.3.0-jre11`)

**What runtime / compiler are you using (e.g., python version or gcc version)**

JRuby 9.3.3.0

**What did you do?**

This will work:

```
data = File.read("path/to/proto.proto", mode: "rb")
proto = SomeProtoClass.decode(data)
proto.to_proto
```

This will explode:

```
data = File.read("path/to/proto.proto", mode: "rb")
proto = SomeProtoClass.decode(data)
proto.inspect
proto.to_proto
```

**What did you expect to see**

Instance converted to proto binary without an error.

**What did you see instead?**

```
Java::JavaLang::NullPointerException: from
com.google.protobuf.jruby.RubyMessage.build(RubyMessage.java:680)","com.google.protobuf.jruby.RubyMessage.convert(RubyMessage.java:858)","com.google.protobuf.jruby.RubyMessage.build(RubyMessage.java:663)","com.google.protobuf.jruby.RubyMessage.build(RubyMessage.java:639)","com.google.protobuf.jruby.RubyMessage.encode(RubyMessage.java:475)","com.google.protobuf.jruby.RubyMessage$INVOKER$s$1$0$encode.call(RubyMessage$INVOKER$s$1$0$encode.gen)","org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372)","org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175)","org.jruby.dist/org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)","org.jruby.dist/org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)","org.jruby.dist/org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)","org.jruby.dist/org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:164)","org.jruby.dist/org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:151)","org.jruby.dist/org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198)","org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:351)","org.jruby.dist/org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:144)","org.jruby.dist/org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345)","org.jruby.dist/org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)","org.jruby.dist/org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)","org.jruby.dist/org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)","org.jruby.dist/org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:66)","org.jruby.dist/org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)","org.jruby.dist/org.jruby.runtime.Block.call(Block.java:143)","org.jruby.dist/org.jruby.RubyProc.call(RubyProc.java:309)","org.jruby.dist/org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)","java.base/java.lang.Thread.run(Unknown Source)"
```

**Anything else we should know about your project / environment**

Only some messages seem to have this issue. We also suspect that methods other than `inspect` may be able to trigger the issue.

This seems to only occur when `decode` is used to build the message from a proto binary string. When the proto is built using the constructor from a hash, everything works fine.

In general, the JRuby version has a ton of bugs relative to the CRuby version. Methods like `dup` plain do not work on the JRuby version (I may create a separate issue about this).

### PR DESCRIPTION
**Pull request by JasonLunn**
Fixes #9507 by:
1. Eliminating the call to the `.toString()` on a possibly `null` object reference
2. Reordering surrounding condition checks so that the the potentially null object reference is never retrieved in the first place.

Either of the solutions would have been sufficient, but the combination of both is slightly more performant in the general case.

### CODE REVIEW

**Comment by haberman** [comment]
Could you add a bit more information? What was the root cause of the bug? What is the strategy for the fix?

**Comment by JasonLunn** [comment]
Description updated.

**Review by haberman — APPROVED** [review]

**Comment by NC-piercej** [comment]
Do we expect this to make it into the upcoming `3.20` release?

**Comment by jorgbrown** [comment]
> Do we expect this to make it into the upcoming `3.20` release?

I would expect it to make it into 3.20.1.

**Pull request merged**
