### PR TITLE
Update protobuf version

### PR DESCRIPTION
**Pull request by rafi-kamal**

### CODE REVIEW

**Comment by rafi-kamal** [comment]
@TeBoring some the PHP files have changed. Do you know why?

**Comment by TeBoring** [comment]
My php fix has some protoc change. That’s expected

**Comment by rafi-kamal** [comment]
The Bazel tests are failing with the following error:

```
ERROR: /tmpfs/src/github/protobuf/examples/BUILD:73:1: //:addressbook_java_lite_proto depends on @com_google_protobuf_javalite//:javalite_toolchain in repository @com_google_protobuf_javalite which failed to fetch. no such package '@com_google_protobuf_javalite//': java.io.IOException: Error downloading [https://github.com/protocolbuffers/protobuf/archive/javalite.zip] to /tmpfs/tmp/bazel/external/com_google_protobuf_javalite/javalite.zip: GET returned 404 Not Found
```

@ejona86 could this be related to the javalite stuffs you have been working on?

**Comment by rafi-kamal** [comment]
Actually, the failure seems to be unrelated to Eric's change (https://github.com/grpc/grpc-java/pull/6424). That change was submitting yesterday, our tests started failing from this noon (https://g3c.corp.google.com/results/invocations;query=protobuf%2Fgithub%2Fmaster%2Fubuntu%2Fbazel%2Fpresubmit).

**Comment by rafi-kamal** [comment]
Looks like our javalite branch got vanished somehow. I've restored the branch, hopefully that will fix the error.

**Pull request merged**
