### PR TITLE
Fix QNX 7.0 support #8593

### PR DESCRIPTION
**Pull request by dschopf**
These changes resolve all issues described in #8593 except for the linker issue.

### CODE REVIEW

**Comment by dschopf** [comment]
@googlebot I signed it!

**Comment by fowles** [comment]
Looks mostly good, but I would like to have Jan take a look because of the aarch64 change in src/google/protobuf/stubs/platform_macros.h

**Comment by pablorcum** [comment]
@dschopf Please include the missing labels `release notes: yes` and `c++` to enable merging.

**Comment by dschopf** [comment]
Sorry, I can't do that, looks like I don't have permission to add or edit labels.

**Review by jtattermusch — COMMENTED** [review]
I don't have any experience with QNX, but the change in  platform_macros.h seems fair
(and it only kicks in when `__QNX__` is defined, so I don't think it can break the aarch64 linux support in any way).
I'll let @fowles to review the rest of the code and give the final approval.

**Review by fowles — APPROVED** [review]

**Pull request merged**
