### PR TITLE
deps: update to Guava 30

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Review by TeBoring — APPROVED** [review]

**Comment by TeBoring** [comment]
The java linkage test failed. Could you take a look?

**Comment by elharo** [comment]
Details is not showing me any info. Did it expire?

**Comment by TeBoring** [comment]
@suztomo could you help take a look of the failure in the linkage test?

**Comment by elharo** [comment]
We can't look because the output has expired and isn't there any more. :-( If you rerun the build, we'll take a look; or if you grant us permissions on the repo, we can run it ourselves.

**Comment by TeBoring** [comment]
Just re-run.

**Comment by suztomo** [comment]
> All checks have passed
> 54 successful checks

Great!

**Comment by elharo** [comment]
Thanks. Can someone merge this?

**Review by TeBoring — APPROVED** [review]

**Pull request merged**
