### PR TITLE
Several Fixes for Protobuf Python Code Generation

### PR DESCRIPTION
**Pull request by diguida**
* Use `pathlib` instead of `glob`
* Remove deprecated `distutils` package in favour of the `setuptools` API (see PEP-632)
* fix recursive lookup of `proto` files
* Increment version to 1.1.0.

### CODE REVIEW

**Comment by diguida** [comment]
@haberman can you see any issues in this PR?
Let me know if you find problems in the proposed changes.

**Comment by haberman** [comment]
Is there a way to add unit tests for this?

**Review by reinasalondra — CHANGES_REQUESTED** [review]
#10309

**Review by reinasalondra — APPROVED** [review]

**Comment by diguida** [comment]
I do not know if I can add a unit test here.
Apart from that, are the changes ok? Do you want me to rebase the branch?

Thanks

**Comment by haberman** [comment]
The changes look fine. I am just concerned that recursive lookup of proto files was broken and we didn't know it. A unit test could help ensure that recursive lookup works.

How are distutils extensions usually tested?

**Comment by diguida** [comment]
> The changes look fine. I am just concerned that recursive lookup of proto files was broken and we didn't know it. A unit test could help ensure that recursive lookup works.
> 
> How are distutils extensions usually tested?

I see your point, and agree.
I can check if the python packaging authority has some guidance about such tests.

**Comment by diguida** [comment]
> > The changes look fine. I am just concerned that recursive lookup of proto files was broken and we didn't know it. A unit test could help ensure that recursive lookup works.
> > 
> > How are distutils extensions usually tested?
> 
> I see your point, and agree.
> I can check if the python packaging authority has some guidance about such tests.

BTW, maybe there could be two further improvements here:
- Use console scripts from setuptools
- Remove output folder if already exists: this guarantees that you always produce updated generated sources, and avoids the OSError if you forget to delete it.

Let me know if I can add at least the latter in this PR.

**Comment by haberman** [comment]
> Remove output folder if already exists: this guarantees that you always produce updated generated sources, and avoids the OSError if you forget to delete it.

How is the output folder specified? Is there any chance that the user might accidentally set the output folder to one of their source folders, and this would end up deleting the user's source files? That would be my main concern, we don't want to accidentally delete the user's precious files.

**Comment by diguida** [comment]
> > Remove output folder if already exists: this guarantees that you always produce updated generated sources, and avoids the OSError if you forget to delete it.
> 
> How is the output folder specified? Is there any chance that the user might accidentally set the output folder to one of their source folders, and this would end up deleting the user's source files? That would be my main concern, we don't want to accidentally delete the user's precious files.

Good point. Basically, a tool should not remove files unless explicitly requested by the user.
If instead the tool fails, the user realizes that something is wrong in the output folder, and can have a look.

**Pull request closed without merging**
