### PR TITLE
[PHP] [3.12.x] Fix GPBUtil::getFullClassName() argument order

### PR DESCRIPTION
**Pull request by davidgrayston**
#7629 for `3.12.x`

### CODE REVIEW

**Comment by davidgrayston** [comment]
@haberman before porting this to `3.12.x`, is it worth double checking that the arguments weren't intentionally swapped for backwards compatibility? It was added in  #4741

**Comment by davidgrayston** [comment]
I think swapping the arguments to the "correct" order will break older generated code (that uses underscores instead of namespace), as `getClass()` is used without falling back on `getLegacyClass()`

**Comment by davidgrayston** [comment]
You could fallback on the legacy class like this https://github.com/davidgrayston/protobuf/commit/233e5e0c63d817fd882d77fa8acc6ef5c11680c2 - or perhaps it would be safest to leave it as is and close this PR?

**Comment by haberman** [comment]
> I think swapping the arguments to the "correct" order will break older generated code (that uses underscores instead of namespace), as getClass() is used without falling back on getLegacyClass()

Can you be more specific? What is the failure scenario?

It's hard to imagine that the old code would have intentionally called `setLegacyClass()` with a non-legacy class name.

@TeBoring do you have any comment?

**Comment by davidgrayston** [comment]
Old code would have class `Foo\TestMessage_Sub`, but not `Foo\TestMessage\Sub`, so code such as the following would fail:

```
$klass = $field->getMessageType()->getClass();
$value = new $klass;
```
(from https://github.com/protocolbuffers/protobuf/blob/master/php/src/Google/Protobuf/Internal/Message.php#L418)

**Comment by haberman** [comment]
The new class names have been generated since Protobuf 3.6.0 in June 2018.

But I agree it may make sense to cut a new minor release for this.

**Comment by davidgrayston** [comment]
ok - adding a fallback (something like this https://github.com/davidgrayston/protobuf/commit/233e5e0c63d817fd882d77fa8acc6ef5c11680c2) should make it safe enough as a bug fix, as it would use the new class if available, and fallback on the legacy class (which would trigger the current deprecation notice).

If this change isn't compatible with old generated code that only has `Message_Sub` classes (without newer `Message\Sub` classes), wouldn't this be too risky even as a new minor?

**Comment by davidgrayston** [comment]
Apologies, I've just spotted your comment on https://github.com/protocolbuffers/protobuf/pull/7689#issuecomment-655106081 - I suppose if there's little chance of this breaking existing code, then it should be alright.

If you did want to add a fallback on the legacy class (to be backwards compatible), I'd be happy to include that in this PR.

**Comment by davidgrayston** [comment]
Closing this PR as #7629 ended up in `3.13.0`

**Pull request closed without merging**
