### PR TITLE
prefer to use single quota than double quota

### PR DESCRIPTION
**Pull request by andyliuliming**
so the code generated passes rubocop check automatically.

### CODE REVIEW

**Comment by andyliuliming** [comment]
@jskeet @liujisi could you please help review ?  : )

**Comment by TeBoring** [comment]
What's rubocop? Is it a standard in ruby?

**Comment by andyliuliming** [comment]
> What's rubocop? Is it a standard in ruby?

it's most a standard in ruby, [rubocop](https://github.com/rubocop-hq/rubocop), many many projects use that for the static analyze for their ruby code.

**Comment by TeBoring** [comment]
Because rubocop hasn't been added to our integration test, your change may have regression later. Do you have time implement a rubocop for us?

**Comment by andyliuliming** [comment]
> Because rubocop hasn't been added to our integration test, your change may have regression later. Do you have time implement a rubocop for us?

sure, could you please tell me the location of the integration test code? so I can add it.

**Comment by TeBoring** [comment]
Feel free to reopen

**Pull request closed without merging**
