### PR TITLE
java: fix #8201 InvalidAnyProtocolBufferException when a protocol Any messa…

### LINKED ISSUE #8201: Provides richer exception information when processing messages and json conversion fails due to the Any type
target ：JAVA ， proto3
**What language does this apply to?**
If it's a proto syntax change, is it for proto2 or proto3?
If it's about generated code change, what programming language?

**Now, when `JsonFormat.printer().print(message)` is executed, if there is a Descriptor pointed to by the Any node that has not been added to the printer, an InvalidProtocolBufferException will be thrown. `JsonFormat.parser()` also faces the same problem when it works. This exception in the scenario has very limited help at runtime.**

**Provide a more specific exception that is different from InvalidProtocolBufferException to describe the TypeUrl/Descriptor required for the missing Any type to read and write, so that the program can take some other remedial measures**

**If an if (type == null) occurs when an IOException is thrown during the execution of `printAny (MessageOrBuilder message)`, then the current processing scheme: `throw new InvalidProtocolBufferException("Cannot find the type of URL:" + typeUrl);` Modify it to: `throw new InvalidAnyProtocolBufferException( "Cannot find the type of url):" + typeUrl, typeUrl);`**

**Additional context**

Now I have a serialization tool, but it relies on InvalidProtocolBufferException.getMessage(), which is very fragile

```
ProtobufSerializer.java:
public class ProtobufSerializer {

    private static final AtomicReference<JsonFormat.Printer> jsonPrinter = new AtomicReference<>(JsonFormat.printer());
    private static final AtomicReference<JsonFormat.Parser> jsonParser = new AtomicReference<>(JsonFormat.parser());

    private static final Set<Descriptors.Descriptor> descriptors = new CopyOnWriteArraySet<>();
    private static final Map<String, Boolean> loadTag = Collections.synchronizedMap(new WeakHashMap<>());

    public static Optional<? extends GeneratedMessageV3> unpackAny(Any pack) {
        return ProtobufTypeCache.findClass(pack.getTypeUrl()).filter(pack::is)
                .map(ThrowingFun.unchecked(pack::unpack));
    }

    public static String toJson(GeneratedMessageV3 messageV3) throws InvalidProtocolBufferException {
        JsonFormat.Printer printer = jsonPrinter.get();
        if (printer == null) throw new RuntimeException("printer not found");
        try {
            return printer.print(messageV3);
        } catch (InvalidProtocolBufferException e) {
            String message = e.getMessage();
            String noPrefixTypeUrl;
            // Fragile code
            if (message.startsWith("Cannot find type for url: type.googleapis.com/")
                    && !loadTag.containsKey(noPrefixTypeUrl = ProtobufUtils.removeGooglePrefix(message))) {
                updateDescriptors(noPrefixTypeUrl);
                return toJson(messageV3);
            } else throw e;
        }
    }

    public static Message fromJson(String json, com.google.protobuf.Message.Builder builder) throws InvalidProtocolBufferException {
        JsonFormat.Parser parser = jsonParser.get();
        if (parser == null) throw new RuntimeException("parser not found");
        try {
            parser.merge(json, builder);
            return builder.build();
        } catch (InvalidProtocolBufferException e) {
            String message = e.getMessage();
            String noPrefixTypeUrl;
            // Fragile code
            if (message.startsWith("Cannot resolve type: type.googleapis.com/")
                    && !loadTag.containsKey(noPrefixTypeUrl = ProtobufUtils.removeGooglePrefix(message))) {
                updateDescriptors(noPrefixTypeUrl);
                return fromJson(json, builder);
            } else throw e;
        }
    }

    private static void updateDescriptors(String nextType) {
        Optional<Descriptors.Descriptor> descOpt = ProtobufTypeCache.findDescriptor(nextType);
        loadTag.put(nextType, descOpt.isPresent());

        Descriptors.Descriptor descriptor = descOpt.orElseThrow(() -> new RuntimeException("no descriptor by " + nextType));
        descriptors.add(descriptor);
        while (!jsonParser.compareAndSet(jsonParser.get(),
                JsonFormat.parser().usingTypeRegistry(JsonFormat.TypeRegistry.newBuilder().add(descriptors).build()))) {
            Thread.yield();
        }
        while (!jsonPrinter.compareAndSet(jsonPrinter.get(),
                JsonFormat.printer().usingTypeRegistry(JsonFormat.TypeRegistry.newBuilder().add(descriptors).build()))) {
            Thread.yield();
        }
    }
}
```

**Hope**

```
public class InvalidAnyProtocolBufferException extends InvalidProtocolBufferException {
    public final String typeUrl;
    public InvalidAnyProtocolBufferException(String desc, String targetType) {
        super(desc);
        this.typeUrl = targetType;
    }
}
```

### PR DESCRIPTION
**Pull request by GeTOUO**
java

release notes: yes

InvalidAnyProtocolBufferException when a protocol Any message being parsed is invalid in some way.   (#8201)

### CODE REVIEW

**Comment by GeTOUO** [comment]
the "release notes: yes"  Does not take effect ???

**Comment by GeTOUO** [comment]
release notes: yes

**Comment by GeTOUO** [comment]
@acozzette help me, thanks.

**Comment by GeTOUO** [comment]
Language:java, release notes: no

**Comment by acozzette** [comment]
@GeTOUO I'm going to close this since we haven't heard any response in a few months, but let us know if you're still interested in working on this and we can reopen it.

**Pull request closed without merging**
