### PR TITLE
Raise KeyError in Python ServiceDescriptor.FindMethodByName (#9592)

### PR DESCRIPTION
**Pull request by tomerv**
* Align Python version with C-extension version
  (python/google/protobuf/pyext/descriptor.cc)
* Update documentation accordingly
* Add unit test

### CODE REVIEW

**Comment by tomerv** [comment]
@mkruskal-google please trigger another kokoro run, I fixed the test that failed before.
@anandolee please review
Thanks!

**Comment by tomerv** [comment]
How can I move this forward?
Seems like there's some problem with "MacOS Python Release" build that isn't related to my changes (but maybe it is? How do I find out?). And also I need someone to look at the actual changes.
Thanks.

**Comment by mkruskal-google** [comment]
> How can I move this forward? Seems like there's some problem with "MacOS Python Release" build that isn't related to my changes (but maybe it is? How do I find out?). And also I need someone to look at the actual changes. Thanks.

I suspect this is a false alarm.  We recently deleted the python release builds, but github doesn't automatically clear deleted tests and just keeps displaying the old result.  Please rebase your branch to refresh these, and I can rerun the tests.  I'll also add a reviewer, as I'm not familiar enough with python proto to determine if this is safe or not

**Comment by tomerv** [comment]
>  Please rebase your branch to refresh these

Done.

**Comment by tomerv** [comment]
@haberman , @mkruskal-google , sorry to be so pushy, but...

https://github.com/protocolbuffers/protobuf/blob/main/CONTRIBUTING.md?plain=1#L66
>  We will try to keep our response time within 7-days but if you don’t get any response in a few days, feel free to comment on the threads to get our attention.

🙂

**Review by esorot — APPROVED** [review]

**Pull request merged**
