### PR TITLE
Fix string subscript out of range when parse command line argument

### PR DESCRIPTION
**Pull request by windpenguin**
this pull request try to solve the issue #5200

### CODE REVIEW

**Comment by windpenguin** [comment]
I signed it!

**Comment by acozzette** [comment]
@windpenguin I noticed that we seem to have already fixed this bug on the master branch with #4016, but we never backported that fix to the 3.5.x branch. Do you want to try backporting that fix? I think that approach may be a bit simpler since calling `c_str()` gives you back a string that is guaranteed to have a null byte at the end.

**Comment by windpenguin** [comment]
@acozzette i checked #4016, but for reason that type of path is wstring on branch 3.5.x and is string on branch master, i add const char* into 3.5.x manually.

**Comment by acozzette** [comment]
Thanks @windpenguin!

**Pull request merged**
