### PR TITLE
Fix jruby support to handle messages nested more than 1 level deep

### PR DESCRIPTION
**Pull request by rdubya**
This fixes https://github.com/protocolbuffers/protobuf/issues/8191

### CODE REVIEW

**Comment by hafixo** [comment]
Duplicate of 
Merge pull requested #8194

**Comment by acozzette** [comment]
Thanks, @rdubya! I believe you will need to add the new test files [here](https://github.com/protocolbuffers/protobuf/blob/468bc193ec155756bccf2b2d9eeb8e003d95ce31/Makefile.am#L1135) to fix the test failures.

**Comment by rdubya** [comment]
Hey @acozzette, sorry about missing that step again. I also updated the test structure to match the other ruby tests better.

**Comment by rdubya** [comment]
@acozzette are those failures something else I need to change? The details links don't give me any info.

**Comment by acozzette** [comment]
@rdubya Sorry about that, I can't see any details either. Let me rerun the tests and see if we get more informative results. If that doesn't fix it then there might be another problem because we have been having some issues with access to the test logs.

**Pull request merged**
