### PR TITLE
Don't use int as index parameter

### PR DESCRIPTION
**Pull request by 2A5F**

### CODE REVIEW

**Review by mcy — APPROVED** [review]

**Comment by jorgbrown** [comment]
Could you clarify what problem this is solving for you?

**Comment by 2A5F** [comment]
Implicit conversions are disabled by lint in my cef project

**Comment by 2A5F** [comment]
size_t -> int -> size_t

**Comment by jorgbrown** [comment]
> Implicit conversions are disabled by lint in my cef project

Can you be more specific about where you're seeing these unwanted conversions?

I'd like to avoid adding extra overloads to such a widely-used API; if I can change the callers, that might be preferable.

**Comment by 2A5F** [comment]
https://github.com/protocolbuffers/protobuf/blob/fbf491a397e8799e47128063a3aca53ebdf58897/src/google/protobuf/has_bits.h#L81-L83

https://github.com/protocolbuffers/protobuf/blob/fbf491a397e8799e47128063a3aca53ebdf58897/src/google/protobuf/has_bits.h#L48

**Comment by 2A5F** [comment]
at line 82

`rhs[i]`

**Comment by sbenzaquen** [comment]
Adding extra overloads is not a good idea. If the old one is not used, then it adds dead code. If the old one is used, then it potentially adds ambiguity on some callers.
Fixing the existing overloads to only take `size_t` would be ok. The template parameter is already `size_t`, so it makes sense to make them the same.

However, imposing your local lint rules on third party project is a losing battle.
This is not the only place where implicit conversions happen in protobuf and we will do not prevent new ones from happening. We can't support arbitrary lint rules that are imposed by users.

**Comment by 2A5F** [comment]
It's not actually lint, it just turns on treating warnings as errors, warning C4245

**Comment by sbenzaquen** [comment]
Who is turning on these warnings?

> A third-party library should not have warnings

It is impossible for a library to satisfy all warnings that a user could turn on. Some warnings are actually contradictory with each other.

**Comment by 2A5F** [comment]
> Who is turning on these warnings?

https://bitbucket.org/chromiumembedded/cef/src/178a44bd182bbc3c9ccfca70f53807e94b6a9fc7/cmake/cef_variables.cmake.in#lines-408

**Pull request closed without merging**
