### PR TITLE
Update text_encoding.py

### PR DESCRIPTION
**Pull request by MRkuan**
Change bytes output to hex array string

### CODE REVIEW

**Comment by acozzette** [comment]
@MRkuan Thank you for the pull request, but unfortunately we can't start reviewing this until the CLA is signed. Let me know if you have any trouble signing the CLA.

**Comment by MRkuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by deannagarcia** [comment]
Closing this due to no response. If you want to come back and sign the CLA, feel free to reopen!

**Comment by MRkuan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request closed without merging**
