### PR TITLE
make bytearray work (again)

### PR DESCRIPTION
**Pull request by jensbjorgensen**
fix is pretty simple, just check if the type is bytearray and get the bytes if it is

addresses issue: https://github.com/protocolbuffers/protobuf/issues/15911

### CODE REVIEW

**Comment by jensbjorgensen** [comment]
I submitted a CLA, not sure why it says above I haven't

**Review by anandolee — APPROVED** [review]

**Comment by jensbjorgensen** [comment]
ok, now I see what happened, I signed the CLA but the email address on the commit didn't match. so I've changed my commit now to have the email address that matches my (this) github account and push'ed -f, I just need to figure out how to get that commit to be the one associated with the pull request?

**Comment by jensbjorgensen** [comment]
Ok I think maybe you have to re-approve then @anandolee ?

**Comment by jensbjorgensen** [comment]
@anandolee sorry to bother, I amended my commit to reflect the email address associated with my github account, but I believe manual intervention may be required by you to let the PR move forward?

**Comment by jensbjorgensen** [comment]
In the failing check (building Examples Win 7.1.1) it doesn't seem like the change I have would've caused this?

**Comment by jensbjorgensen** [comment]
hello, could someone take a look at this? I think the win7.1 test failure was unrelated to my change

**Comment by jensbjorgensen** [comment]
I think maybe this needs to be re-approved then @anandolee ?

**Comment by jensbjorgensen** [comment]
@haberman it seems as though it is blocked (again), with "2 workflows awaiting approval", is this something you need to approve?

**Comment by jensbjorgensen** [comment]
@haberman is there maybe something you need to do to move the change along now?

**Review by haberman — APPROVED** [review]

**Comment by jensbjorgensen** [comment]
Hmmm... it just says "Merging is blocked" now, I guess someone authorized needs to click the "Merge pull request" button?

**Comment by haberman** [comment]
The PR should not be merged directly. It will be applied as a CL internally and then propagated back to GitHub.

This workflow is triggered automatically when an approved PR passes all tests. I had forgotten that the most recent commit needs to be approved, which is why the workflow did not trigger before.

There is one more manual approval that must happen internally before the CL is submitted. But I think we should be able to get this in today. Thanks for your patience.

**Pull request closed without merging**
