### PR TITLE
Fix reflection access when using old generated code

### LINKED ISSUE #6822: Current head C# code throws ArgumentNullException when retrieving descriptors with extensions
**What version of protobuf and what language are you using?**
Version: master
Language: C#

**What operating system (Linux, Windows, ...) and version?**

Windows 10.

**What runtime / compiler are you using (e.g., python version or gcc version)**

protoc from 3.10.1 on Windows

**What did you do?**

Proto file test.proto:

```proto
syntax = "proto3";
import "extensions.proto";
message TestMessage {}
```

Proto file extensions.proto:

```proto
syntax = "proto3";
import "google/protobuf/descriptor.proto";
extend google.protobuf.MethodOptions {
  string method_ext = 1234567;
}
```

Generate code:

```sh
protoc.exe -I. -Ipath/to/tools test.proto extensions.proto --csharp_out=.
```

C# code:

```csharp
using System;

class Program
{
    static void Main(string[] args)
    {
        var descriptor = TestMessage.Descriptor;
        Console.WriteLine(descriptor);
    }
}
```

**What did you expect to see**

The descriptor.

**What did you see instead?**

The following exception - full paths removed for simplicity.

```text
Unhandled exception. System.TypeInitializationException: The type initializer for 'TestReflection' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'extension')
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name) in ProtoPreconditions.cs:line 57
   at Google.Protobuf.ExtensionRegistry.Add(Extension extension) in ExtensionRegistry.cs:line 80
   at Google.Protobuf.ExtensionRegistry.AddRange(IEnumerable`1 extensions) in ExtensionRegistry.cs:line 94
   at Google.Protobuf.Reflection.FileDescriptor.AddAllExtensions(FileDescriptor[] dependencies, GeneratedClrTypeInfo generatedInfo, ExtensionRegistry registry) in FileDescriptor.cs:line 447
   at Google.Protobuf.Reflection.FileDescriptor.FromGeneratedCode(Byte[] descriptorData, FileDescriptor[] dependencies, GeneratedClrTypeInfo generatedCodeInfo) in FileDescriptor.cs:line 422
   at TestReflection..cctor() in Test.cs:line 27
   --- End of inner exception stack trace ---
   at TestReflection.get_Descriptor() in Test.cs:line 18
   at TestMessage.get_Descriptor() in Test.cs:line 45
   at Program.Main(String[] args) in Program.cs:line 7
```

### PR DESCRIPTION
**Pull request by jskeet**
Fixes #6822.

### CODE REVIEW

**Comment by jtattermusch** [comment]
This needs to be backported to 3.10.x as well?

**Comment by jtattermusch** [comment]
Ooops it looks like I forgot to trigger the tests (The settings of the protobuf github projects don't enforce that the tests are triggered, which makes it easy to miss that)

@rafi-kamal you should add a "Required" test status for one of the test suites (e.g. "Bazel"), that way if tests are not triggered, PR will be unmergeable.
https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks

**Comment by jtattermusch** [comment]
@rafi-kamal  can you check the status of the tests on master and revert if this PR broke anything?

**Comment by jskeet** [comment]
@jtattermusch: Yes, I *suspect* this needs to be backported to 3.10.x. Will try to create a PR for that (and the other one) in the next day or two.

**Comment by jtattermusch** [comment]
Problem: (OldExtensions2.cs and OldExtensions1.cs) didn't get added to Makefile.am (and I forgot to trigger the tests and merged to soon because I didn't notice that).

**Comment by jskeet** [comment]
I *did* add them to Makefile.am - should I have added them in multiple places?

**Comment by ObsidianMinor** [comment]
The proto files were added but not the corresponding generated code.

**Comment by jskeet** [comment]
Ah, whoops - will create a PR for that later. Doh.

**Pull request merged**
