### PR TITLE
Fix 9825, Java's memoized hash code can fail to be memoized.

### PR DESCRIPTION
**Pull request by shawjef3**
Fixes https://github.com/protocolbuffers/protobuf/issues/9825.

### CODE REVIEW

**Comment by elharo** [comment]
Another possible fix occurs to me. I'm not sure this is actually better, but let me rough it out. The problem is that any flag value like 0 or 989798782 we pick to mean "unmemoized" can also be a valid hash value. Here's my idea:

1. Pick a number such as 5003231 that is slightly less likely to show up by accident than 0 to indicate unmemoized.
2. If it does show up in the calculation, then add 1 and use that as the hash code.

This means that we will be deliberately combining two buckets. That is all the protos that now hash to 5003231 get mixed up with protos that hash to 5003232. However hash collisions are expected and handled. There are more protos than ints after all. 

This feels simpler than carrying around an extra non-final protected field, which is an API level change that technically would require a Tier 2 review. Thoughts?

**Comment by shawjef3** [comment]
I suppose 5003231 is better than 0 as a guard value. @elharo your idea has merit.

I picked adding a boolean with the reasoning that past generated code will be compatible with the new library. They'll continue with the bug. Only newly generated code will require the new library.

For 4.0.x at least, changing the API should be okay since it's not released yet.

**Comment by perezd** [comment]
Let's use this one as the PR of record.

**Comment by elharo** [comment]
@shawjef3 I too am concerned about the extra weigh of an additional boolean field on every message. Memory size of proto messages is a large and growing concern for us. 

I think a modification of the hashCode method would still be forwards and backwards compatible. I'm not sure whether adding a non-private, non-final boolean field is or is not compatible. I'd need to think more about that.

**Comment by shawjef3** [comment]
@elharo an incompatibility would arise if someone used a new protoc compiler version with an AbstractMessageLite that was older, so it didn't have boolean flag.

**Comment by shaod2** [comment]
I was a little lost here.

From the discussion above, we have 2 options. (1) modification of hashCode (2) adding a boolean field.

I agreed (1) is forwards and backwards compatible, and from last comment, (2) will break if new gencode uses old runtime.

Then, isn't the only option to be non-breaking both ways is to modify the hashCode?

**Comment by deannagarcia** [comment]
Closing due to no response, feel free to reopen with the comments addressed.

**Pull request closed without merging**
