### PR TITLE
Fix CMake shared library build using utf8_range and utf8_valid

### PR DESCRIPTION
**Pull request by Chekov2k**
Instead of hardcoding static libraries, allow using the BUILD_SHARED_LIBS behaviour to allow the build of shared utf8 libraries.

### CODE REVIEW

**Comment by hlopko** [comment]
Hi [Chekov2k](https://github.com/Chekov2k), could you please sign the CLA? Unfortunately cannot accept your contribution without it.

**Comment by Chekov2k** [comment]
> Hi [Chekov2k](https://github.com/Chekov2k), could you please sign the CLA? Unfortunately cannot accept your contribution without it.

I'm a bit confused, if I click this link https://github.com/protocolbuffers/protobuf/pull/14867/checks?check_run_id=19090370328 it says I have signed it. Is there something I need to do to this pull request?

**Comment by hlopko** [comment]
Ah, seems the check was stale, it is green now, thank you!

**Comment by zhangskz** [comment]
Is this for #14958?

**Review by coryan — APPROVED** [review]

**Review by zhangskz — APPROVED** [review]

**Comment by Chekov2k** [comment]
Any idea if that can be merged?

**Comment by zhangskz** [comment]
Thanks for re-pinging. Looks like this got stuck for some reason (logs were garbage collected already so I'm not sure why). I've gone ahead and imported this for submission -- please reping if you don't see this merged within the next ~day or so!

**Comment by Chekov2k** [comment]
Thank you :-) will do!

**Pull request closed without merging**
