### PR TITLE
Use ReadVarint32 for Int32 types

### PR DESCRIPTION
**Pull request by rkevingibson**
This adds TYPE_INT32 to the set of 32-bit varint types when selecting a size, along with SINT32 and UINT32. Messages with int32 fields would use ReadVarint64, which would trigger compiler warnings on MSVC.

### CODE REVIEW

**Comment by gregstoll** [comment]
@rkevingibson - I think you need to add the "release notes: no" label to pass the "Mergeable" check.

(thanks for fixing this, these warnings are driving me crazy!)

**Review by dlj-NaN — APPROVED** [review]

**Review by dlj-NaN — CHANGES_REQUESTED** [review]
Ah, right... the descriptor protos also need to be updated. This script should do it, or at least show you the steps (if you want to run them by hand):
https://github.com/protocolbuffers/protobuf/blob/master/generate_descriptor_proto.sh

**Comment by gregstoll** [comment]
@dlj-NaN Thanks for the pointer! I forked @rkevingibson's fork [here](https://github.com/gregstoll/protobuf) and regenerated the descriptor protos, and now "make check" passes. Is there a way I can update this PR, or should I just make a new one?

**Comment by rkevingibson** [comment]
@gregstoll Thanks for doing that, I'll cherry-pick your changes in this PR, I had some trouble regenerating (I'm building on windows)

**Comment by gregstoll** [comment]
@googlebot I fixed it.

**Comment by gregstoll** [comment]
@googlebot I consent.

**Comment by gregstoll** [comment]
@dlj-NaN - is there a way to request you take a look at this again? My apologies - I'm new at using GitHub PR's, and I don't seem to have an option to reset your review.

**Comment by gregstoll** [comment]
Hi @acozzette - would you mind taking a look at this? It's a pretty small change and has been open for a while. Thanks!

**Comment by acozzette** [comment]
Thanks for fixing this!

**Pull request merged**
