### PR TITLE
JSON conformance test: repeated with a mix of known and unknown enum string values

### PR DESCRIPTION
**Pull request by antongrbin**
This test was suggested by @jskeet in the related issue: https://github.com/protocolbuffers/protobuf/issues/7392#issuecomment-1884666885

I am not confident that the failure lists are comprehensive (I only run a few tests locally) -- will fix once we get CI results.

### CODE REVIEW

**Review by jskeet — COMMENTED** [review]
This looks good to me, but should we have another with a map containing a mixture of known and unknown values? (I hadn't appreciated that aspect until I implemented it...)

**Review by jskeet — APPROVED** [review]
Looks good to me, thanks! Over to @zhangskz for protobuf team approval.

**Comment by antongrbin** [comment]
@zhangskz thank you for your review! Let me know if there are next steps for me here -- currently we are blocked on internal checks.

**Comment by zhangskz** [comment]
Thanks for the ping! Looks like this got stuck on some internal tests that needed the new tests added to their internal failure lists as well. I've patched your change which should land automatically (See https://github.com/protocolbuffers/protobuf/pull/15922) once approved.

Please give us another ping if you don't see this go in within a day or so!

**Pull request closed without merging**
