### PR TITLE
C#: repeated field functional improvement

### PR DESCRIPTION
**Pull request by 893949088**
#6182

### CODE REVIEW

**Comment by 893949088** [comment]
@googlebot I signed it!

**Comment by 893949088** [comment]
@BSBandme

**Comment by 893949088** [comment]
@jtattermusch I hope get any one reply about this pull request.

**Comment by jtattermusch** [comment]
I think repeated fields not being settable is working as intended. I think there are scenarios when enabling the setter can cause unexpected results and therefore it's safer to only allow the getter.
What is the motivation for this change?

**Pull request closed without merging**
