### PR TITLE
Add `protobuf_java_lite` Bazel target

### PR DESCRIPTION
**Pull request by cgrushko**
that builds the JavaLite runtime

### CODE REVIEW

**Comment by haon4** [comment]
Thanks. How did you come up with this list? Is it coming from https://github.com/protocolbuffers/protobuf/blob/master/java/lite/pom.xml? Can you add a comment in both files to keep them in sync?

**Comment by cgrushko** [comment]
Oh. I didn't notice the `pom.xml` file. I just copied the list from the `javalite` branch and kept adding files until it built /shrug.
Let me copy the list from `pom.xml`.

**Comment by cgrushko** [comment]
Actually, my list is missing the following files:

* AllocatedBuffer.java
* BinaryWriter.java
* BufferAllocator.java
* GeneratedExtensionRegistryLoader.java
* ProtoField.java
* ProtoMessage.java
* ProtoOneof.java
* ProtoOneofCase.java
* ProtoPresenceBits.java
* ProtoPresenceCheckedField.java
* ProtobufLists.java

But other than the first two (IIUC are used in an experimental serializer), I don't see these files in `master`.

**Comment by cgrushko** [comment]
Actually, my list is missing the following files:

* AllocatedBuffer.java
* BinaryWriter.java
* BufferAllocator.java
* GeneratedExtensionRegistryLoader.java
* ProtoField.java
* ProtoMessage.java
* ProtoOneof.java
* ProtoOneofCase.java
* ProtoPresenceBits.java
* ProtoPresenceCheckedField.java
* ProtobufLists.java

But other than the first two (IIUC are used in an experimental serializer), I don't see these files in `master`.

**Comment by haon4** [comment]
Ooops! Silly me, seems like there are more internal things that I missed.

**Comment by haon4** [comment]
lite/pom.xml is fixed. Can you update description in the BUILD file and lite/pom.xml to tell developers to keep them in sync?

**Comment by haon4** [comment]
Closing due to no activity. Please reopen if still needed.

**Pull request closed without merging**
