### PR TITLE
Add ruby 2.6 gem build for linux

### PR DESCRIPTION
**Pull request by TeBoring**

### CODE REVIEW

**Comment by TeBoring** [comment]
Failed tests seem to be caused by the new mac image from kokoro.

**Comment by TeBoring** [comment]
This change modifies the script to build ruby gems, which should not be related to all these failing tests.

**Comment by Envek** [comment]
@oggy this works for me:
```ruby
# Gemfile
gem "google-protobuf", git: "https://github.com/protocolbuffers/protobuf"
```
Isn't it works for you?

**Comment by aadityataparia** [comment]
@Envek this doesn't work,

**Comment by oggy** [comment]
@Envek No. It bundles ok, but because there are ruby files that need to be generated before the gem is built, you can't, e.g., `require 'google/protobuf/struct_pb'`.

**Comment by Envek** [comment]
@oggy, @aadityataparia, @romansklenar, then try to set `BUNDLE_FORCE_RUBY_PLATFORM` environment variable to `1` to make Bundler ignore precompiled binaries and thus build them from scratch.

See https://github.com/protocolbuffers/protobuf/issues/4460#issuecomment-434631296 for reference.

**Pull request merged**
