### PR TITLE
Fix Issue #5345

### PR DESCRIPTION
**Pull request by Allmoz**
Added a few \ on the comments to match the exceptions scope when is referenced while in a namespace. So the IDEs can be happy.

I think i got them all.

Best regards!

### CODE REVIEW

**Comment by Allmoz** [comment]
I signed it!

**Comment by TeBoring** [comment]
Could you also update the code generator in src/google/protobuf/compiler/php

**Comment by Allmoz** [comment]
you mean adding the "* @throws \Exception" to the setters?

**Comment by TeBoring** [comment]
I mean, for whatever changes to make in php code, could you add the logic to our code generator? So that, next time, we won't have regression.

**Comment by Allmoz** [comment]
Ok, but for the changes i made i did not find the compiler routines that made it (if it was made by it)

**Comment by TeBoring** [comment]
Ah, you are right. Code you modified were made manually.

**Pull request merged**
