### PR TITLE
Fix error: unused parameter 'arena' [-Werror=unused-parameter]

### PR DESCRIPTION
**Pull request by Thomas-Barbier-1A**

### CODE REVIEW

**Comment by Thomas-Barbier-1A** [comment]
I signed it!

**Comment by acozzette** [comment]
@Thomas-Barbier-1A Thanks for the pull request! I am just trying to make sure the CLA checker bot is happy. Did you sign the CLA as an individual or as part of a corporate CLA?

**Comment by Thomas-Barbier-1A** [comment]
@acozzette actually there is already a Corporate CLA signed by my company. I didn't sign an individual one. Maybe I need to sign both?

**Comment by Thomas-Barbier-1A** [comment]
I signed it!

**Pull request merged**
