### PR TITLE
[Ruby] Fix RepeatedField#last, #first inconsistencies

### PR DESCRIPTION
**Pull request by lucthev**
`RepeatedField#last(n)` has an off-by-one error resulting in one more element being returned than requested.

While I was at it, I also fixed the following inconsistencies with `Array`:

- `last(n)` where n > size should return all elements; the current implementation wraps around such that e.g. `last(size + 2) == last(2)`
- `last(n)` where n < 0 should raise an `ArgumentError`

### CODE REVIEW

**Review by fowles — APPROVED** [review]

**Comment by fowles** [comment]
This looks good.  I will merge it after our test suite finishes

**Comment by fowles** [comment]
Looks like the failure is in jruby.  Jason?

**Comment by JasonLunn** [comment]
It appears that the fix for this issue has uncovered a separate bug in the JRuby implementation of the `at` (aka `[]`) method of [`RubyRepeatedField`](https://github.com/protocolbuffers/protobuf/blob/main/ruby/src/main/java/com/google/protobuf/jruby/RubyRepeatedField.java#L131). It appears that the implementation is making assumptions [here](https://github.com/protocolbuffers/protobuf/blob/main/ruby/src/main/java/com/google/protobuf/jruby/RubyRepeatedField.java#L145) about the range values that don't hold if you use negative indices to count back from the end of the sequence.

@lucthev - if you're comfortable working in Java, you can fix both issues in the same PR. If not, please open a separate ticket for the JRuby-specific issue and I can work up a patch.

**Comment by fowles** [comment]
rerunning test suite.  Will come back tomorrow to see how it went

**Comment by lucthev** [comment]
Thanks for the reviews! I had a stab at fixing the issue in `RubyRepeatedField#[]` but there's a lot of odd edge-cases (and I'm not very familiar with Java) so I didn't get very far. I've opened https://github.com/protocolbuffers/protobuf/issues/9751 to track that issue just for completeness (it's pretty niche anyways).

In the meantime, I've worked around that in this PR by not using a negative index.

**Pull request merged**
