### PR TITLE
JRuby fixes for 3.20.x

### PR DESCRIPTION
**Pull request by JasonLunn**
Cherry pick JRuby changes that fix NPE during encoding (#9507) and implements `respond_to?` (#9202) into 3.20.x.

### CODE REVIEW

**Comment by jorgbrown** [comment]
Can you change the description to be more specific, i.e. something like

Merge JRuby fixes, "Fix NPE during encoding" and "Implement respond_to" into 3.20.x

**Comment by JasonLunn** [comment]
> Can you change the description to be more specific, i.e. something like
> 
> Merge JRuby fixes, "Fix NPE during encoding" and "Implement respond_to" into 3.20.x

Done.

**Comment by jorgbrown** [comment]
One nit:

9507 is an issue number <https://github.com/protocolbuffers/protobuf/issues/9507> while 9677 is a pull request number <https://github.com/protocolbuffers/protobuf/pull/9677>

Can you change "9507" to "9637"?

ps Sorry I didn't see this earlier but I thought the title at the top would reflect the change, as opposed to just the first line of the "Conversation" section.

**Comment by jorgbrown** [comment]
LGTM

**Pull request merged**
