### PR TITLE
Add a test for bazel-built dist archives

### PR DESCRIPTION
**Pull request by dlj-NaN**
This adds a Kokoro build definition to run Bazel tests inside of a bazel-built distribution tree.

Notably, the distribution archives use the WORKSPACE file to retrieve deps. Sources such as googletest are not vendored in the archive.

### CODE REVIEW

**Review by deannagarcia — APPROVED** [review]
Can we also test that cmake builds work? And any other build system we support?

**Review by acozzette — APPROVED** [review]

**Comment by dlj-NaN** [comment]
> Can we also test that cmake builds work? And any other build system we support?

I don't think the Bazel-built archive will work for cmake, since it doesn't include abseil or googletest sources. The closest existing build is cpp_distcheck, which validates automake.

**Comment by deannagarcia** [comment]
Can we use these dist archives if they don't compile for cmake? I thought that was a requirement?

If they are going to need to support cmake but just don't yet can we leave a TODO to test a cmake build?

**Comment by dlj-NaN** [comment]
> Can we use these dist archives if they don't compile for cmake? I thought that was a requirement?
> 
> If they are going to need to support cmake but just don't yet can we leave a TODO to test a cmake build?

That's a good idea, but I'm not sure where to record that. We wouldn't want to do the cmake build here, since that would just ~double the execution time... we probably want a separate build for that.

I think there is probably some refactoring that could be done as well, though, at which point there should be a natural cut point. I will send you a couple of follow-ups for that.

**Pull request merged**
