### PR TITLE
Set exit status to 1 when fatal_warnings flag is on

### LINKED ISSUE #10486: protoc cli returns success with --fatal_warnings switch when warnings are detected
Version: libprotoc 3.19.4
Language: NA
OS: OSX, installed via brew

1. open a terminal (I use zsh)
2. decode a protobuf file for which a warning will be emitted using the `--fatal_warnings` switch
3. check the command return value

```
$ cat temp.in.pbuf | protoc  --decode job_definition.job_t --fatal_warnings --proto_path ~/workspace/engine/proto/ job.proto > /dev/null
warning:  Input message is missing required fields:  country[0].id, country[1].id
$ echo $?
0
```

notice the contract include 
```
message country_t {
	required int32 id = 1;
	required string country = 2;
}
```

and the encode file does not indeed have an `id` field, i.e. the warning is correct.

**What did you expect to see**
protoc shall return a non-zero error

**What did you see instead?**
protoc returns 0

### PR DESCRIPTION
**Pull request by junekhan**
This fixes #10486

### CODE REVIEW

**Comment by zhangskz** [comment]
3.19.x is out of support. This should instead be checked into the main branch, to be include in the next minor release and/or CP'ed into latest supported release branch.

https://protobuf.dev/support/version-support/#cpp

**Review by fowles — APPROVED** [review]

**Comment by junekhan** [comment]
> 3.19.x is out of support. This should instead be checked into the main branch, to be include in the next minor release and/or CP'ed into latest supported release branch.
> 
> https://protobuf.dev/support/version-support/#cpp

@zhangskz got it. I'll author another PR during this weekend.

**Comment by fowles** [comment]
> > 3.19.x is out of support. This should instead be checked into the main branch, to be include in the next minor release and/or CP'ed into latest supported release branch.
> > https://protobuf.dev/support/version-support/#cpp
> 
> @zhangskz got it. I'll author another PR during this weekend.

Generally speak, prefer to author on truck and back port to earlier releases.  Trunk has the strongest testing.

**Comment by zhangskz** [comment]
Thanks for the contribution! I'll close this PR in favor of a new one to main branch. Feel free to link to this PR in the new one, which should help speed up the review process.

**Pull request closed without merging**
