### PR TITLE
Cherry-pick zlib Bazel support

### PR DESCRIPTION
**Pull request by schroederc**
Cherry-pick #5389 into 3.7.x release

### CODE REVIEW

**Comment by acozzette** [comment]
@schroederc The CI run is showing a Bazel error, do you know what that is about?

**Comment by acozzette** [comment]
Could you also include a cherry-pick of e03c0d22a76c302b9af50260817eb9cc10b800bc? That one fixes the `examples/` directory to handle this change.

**Comment by schroederc** [comment]
I'm not completely sure about the build failure:

```
ERROR: error loading package '': Encountered error while reading extension file 'lib/versions.bzl': no such package '@bazel_skylib//lib': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
ERROR: error loading package '': Encountered error while reading extension file 'lib/versions.bzl': no such package '@bazel_skylib//lib': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
```

However, my guess is that the CI instance that is building the examples is (1) caching the workspace resolution of external repositories and (2) `com_google_protobuf` is pinned to a `master` commit before 31232c9b1e27f3c683dfdec25de6c6f18e66c0a2.

**Comment by acozzette** [comment]
I thought that Bazel error might be related to #5490, but I see that for some reason the check is passing now.

**Comment by acozzette** [comment]
Thanks @schroederc!

**Pull request merged**
