### PR TITLE
add mingw_gcc_compiler config_setting to zlib.BUILD

### LINKED ISSUE #16024: Build protobuf from source fails with Bazel MINGW GCC toolchain under Windows.
**What version of protobuf and what language are you using?**

Version: 27-dev
Language: C++

**What operating system**

Windows 11

**What runtime / compiler are you using (e.g., python version or gcc version)**

mingw-w64-ucrt-x86_64 MSYS package with gcc 13.2.0
bazel 7.0.1

**What did you do?**

- clone protobuf main branch
- modify .bazelrc and WORKSPACE as explained [here](https://github.com/vvviktor/bazel-mingw-toolchain.git)
- run `bazel build :protoc :protobuf --compilation_mode dbg --verbose_failures`
- comment "-Werror" flag in `"\..\protobuf\build_defs\cpp_opts.bzl"`

**What did you expect to see**

Build completed successfully.

**What did you see instead?**

Build fails while processing zlib external target with these errors:
```
external/zlib~1.3.1/gzlib.c: In function 'gzFile_s* gz_open(const void*, int, const char*)':
external/zlib~1.3.1/gzlib.c:183:30: error: invalid conversion from 'const void*' to 'const wchar_t*' [-fpermissive]
  183 |         len = wcstombs(NULL, path, 0);
      |                              ^~~~
      |                              |
      |                              const void*
In file included from C:/msys64/ucrt64/include/c++/13.2.0/cstdlib:79,
                 from C:/msys64/ucrt64/include/c++/13.2.0/stdlib.h:36,
                 from external/zlib~1.3.1/gzguts.h:24,
                 from external/zlib~1.3.1/gzlib.c:6:
C:/msys64/ucrt64/include/stdlib.h:531:82: note:   initializing argument 2 of 'size_t wcstombs(char*, const wchar_t*, size_t)'
  531 |   size_t __cdecl wcstombs(char * __restrict__ _Dest,const wchar_t * __restrict__ _Source,size_t _MaxCount) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
      |                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/zlib~1.3.1/gzlib.c:198:35: error: invalid conversion from 'const void*' to 'const wchar_t*' [-fpermissive]
  198 |             wcstombs(state->path, path, len + 1);
      |                                   ^~~~
      |                                   |
      |                                   const void*
C:/msys64/ucrt64/include/stdlib.h:531:82: note:   initializing argument 2 of 'size_t wcstombs(char*, const wchar_t*, size_t)'
  531 |   size_t __cdecl wcstombs(char * __restrict__ _Dest,const wchar_t * __restrict__ _Source,size_t _MaxCount) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
      |                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/zlib~1.3.1/gzlib.c:233:27: error: invalid conversion from 'const void*' to 'const wchar_t*' [-fpermissive]
  233 |         fd == -2 ? _wopen(path, oflag, 0666) :
      |                           ^~~~
      |                           |
      |                           const void*
In file included from C:/msys64/ucrt64/include/fcntl.h:8,
                 from external/zlib~1.3.1/gzguts.h:31:
C:/msys64/ucrt64/include/io.h:316:45: note:   initializing argument 1 of 'int _wopen(const wchar_t*, int, ...)'
  316 |   _CRTIMP int __cdecl _wopen(const wchar_t *_Filename,int _OpenFlag,...) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
      |                              ~~~~~~~~~~~~~~~^~~~~~~~~
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

### PR DESCRIPTION
**Pull request by vvviktor**
Fixes #16024 

Workaround to avoid bazel build failure using MinGW GCC toolchain under Windows. These changes suppress `[-fpermissive]` errors while compiling zlib external dependency with mingw-gcc toolchain.

### CODE REVIEW

**Comment by haberman** [comment]
It looks like `-fpermissive` will treat errors like warnings.

I don't think we want to do this. What errors are you getting in the mingw build?

**Comment by vvviktor** [comment]
> It looks like `-fpermissive` will treat errors like warnings.
> 
> I don't think we want to do this. What errors are you getting in the mingw build?

Thanks for reply. I'm getting these errors building protobuf with Bazel with mingw toolchain:
```
external/zlib~1.3.1/gzlib.c: In function 'gzFile_s* gz_open(const void*, int, const char*)':
external/zlib~1.3.1/gzlib.c:183:30: error: invalid conversion from 'const void*' to 'const wchar_t*' [-fpermissive]
  183 |         len = wcstombs(NULL, path, 0);
      |                              ^~~~
      |                              |
      |                              const void*
In file included from C:/msys64/ucrt64/include/c++/13.2.0/cstdlib:79,
                 from C:/msys64/ucrt64/include/c++/13.2.0/stdlib.h:36,
                 from external/zlib~1.3.1/gzguts.h:24,
                 from external/zlib~1.3.1/gzlib.c:6:
C:/msys64/ucrt64/include/stdlib.h:531:82: note:   initializing argument 2 of 'size_t wcstombs(char*, const wchar_t*, size_t)'
  531 |   size_t __cdecl wcstombs(char * __restrict__ _Dest,const wchar_t * __restrict__ _Source,size_t _MaxCount) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
      |                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/zlib~1.3.1/gzlib.c:198:35: error: invalid conversion from 'const void*' to 'const wchar_t*' [-fpermissive]
  198 |             wcstombs(state->path, path, len + 1);
      |                                   ^~~~
      |                                   |
      |                                   const void*
C:/msys64/ucrt64/include/stdlib.h:531:82: note:   initializing argument 2 of 'size_t wcstombs(char*, const wchar_t*, size_t)'
  531 |   size_t __cdecl wcstombs(char * __restrict__ _Dest,const wchar_t * __restrict__ _Source,size_t _MaxCount) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
      |                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/zlib~1.3.1/gzlib.c:233:27: error: invalid conversion from 'const void*' to 'const wchar_t*' [-fpermissive]
  233 |         fd == -2 ? _wopen(path, oflag, 0666) :
      |                           ^~~~
      |                           |
      |                           const void*
In file included from C:/msys64/ucrt64/include/fcntl.h:8,
                 from external/zlib~1.3.1/gzguts.h:31:
C:/msys64/ucrt64/include/io.h:316:45: note:   initializing argument 1 of 'int _wopen(const wchar_t*, int, ...)'
  316 |   _CRTIMP int __cdecl _wopen(const wchar_t *_Filename,int _OpenFlag,...) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
      |                              ~~~~~~~~~~~~~~~^~~~~~~~~
```

Full explanation is here: #16024

**Comment by vvviktor** [comment]
@haberman 
These default opts:
```
  copts = select({
        "@platforms//os:windows": [],
        "//conditions:default": [
            "-Wno-deprecated-non-prototype",
            "-Wno-unused-variable",
            "-Wno-implicit-function-declaration",
        ],
    }),
```
look more clang-specific. I use GCC, so `-Wno-deprecated-non-prototype` and '-Wno-implicit-function-declaration' are unrecognized. May be some other options should be set specifically for GCC?

**Comment by vvviktor** [comment]
@haberman 

If I add following flags :
```
        "-Wno-maybe-uninitialized",
        "-Wno-unused-parameter",
        "-Wno-missing-field-initializers",
        "-Wno-implicit-fallthrough",
        "-Wno-redundant-move",
```
to `protobuf\build_defs\cpp_opts.bzl` right after `-Werror`, protoc compiles successfully. But, anyway, I have to keep `-fpermissive` in `protobuf\third_party\zlib.BUILD` as external `zlib` won't compile without it.

**Comment by haberman** [comment]
I chatted with some people on the team, and I don't think we intended for user builds to get `-Werror`.

I think we'd prefer to remove `-Werror` from the build rather than add mingw-specific flags.

**Comment by acozzette** [comment]
I'm going to close this because it should no longer be needed, now that 5695a882bd93b8ae4803f220a448785dc868a876 removed `-Werror` from our BUILD files. Please let me know if I am wrong about that, though.

**Pull request closed without merging**
