### PR TITLE
Fix broken WORKSPACE link

### PR DESCRIPTION
**Pull request by gampu**
Cleanup.

### CODE REVIEW

**Review by deannagarcia — APPROVED** [review]
Thanks for this fix! As soon as you complete the CLA I will go ahead and merge

**Comment by gampu** [comment]
I have signed the CLA using my primary gmail address but the GitHub commit uses 43856776+gampu@users.noreply.github.com. How can I fix this?

**Comment by acozzette** [comment]
You should be able to fix the email address by configuring your email address in Git (`git config user.email "username@gmail.com"`), amending your commit (`git commit --amend --reset-author`), and then force-pushing it (`git push -f`).

**Comment by gampu** [comment]
The existing link seems to be valid now. As a result, closing the PR.

**Pull request closed without merging**
