### PR TITLE
Merge 3.7.x into master

### PR DESCRIPTION
**Pull request by acozzette**
The 3.7.x branch has a bunch of fixes for 3.7.1, so let's merge them into master.

### CODE REVIEW

**Comment by acozzette** [comment]
The CLA is OK because this pull request is just merging commits that have already gone through the CLA process.

**Comment by TeBoring** [comment]
upb for php and ruby is complicate to merge. I will send append a PR to this change to fix that.

**Comment by TeBoring** [comment]
bazel test still fails. @acozzette could you take a look?

**Comment by acozzette** [comment]
@TeBoring I made one more commit which I think should fix that

**Pull request merged**
