### PR TITLE
options: reserved extension range for CSI

### PR DESCRIPTION
**Pull request by jdef**

### CODE REVIEW

**Comment by jdef** [comment]
I signed it!

**Comment by jdef** [comment]
@xfxyjwf PTAL

**Comment by jdef** [comment]
@jskeet PTAL

**Comment by jskeet** [comment]
I'm not the right person to review this, I'm afraid.

**Comment by jdef** [comment]
@jskeet can you point me in the right direction? would like to get this approved sooner than later

**Comment by jskeet** [comment]
I'm afraid I really don't know - I'm not in the protobuf team.

Let's see if @acozzette, @anandolee or @TeBoring can help.

**Pull request merged**
