### PR TITLE
Python compiler takes keywords into account then generating code for top level enums.

### LINKED ISSUE #4833: Python reserved word 'None' is not considered in code generation
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: Python

**What operating system (Linux, Windows, ...) and version?**
Windows 10

**What runtime / compiler are you using (e.g., python version or gcc version)**
Python 3.6.5

**What did you do?**
1. Define Enum

```
enum NotificationType {
    None = 0;
    Type1 = 1;
    Type2 = 2;
    Type3 = 3;
}
```

2. Compile to Python

`protoc.exe -I=.\pb --python_out=.\pb_python .\pb\test.proto`

3. Run it in Python

**What did you expect to see**
No Error

**What did you see instead?**
```
  File "test.py", line 10
    None = 0
SyntaxError: cannot assign to None
```

### PR DESCRIPTION
**Pull request by yoks**
At the moment protobuf compiler for Python is not taking into account Python keywords then generating top level enums e.g. following pb:
```protobuf
syntax = "proto3";

enum TestEnum {
    None = 0;
    Something = 1;
    for = 2;
    class = 3;
}
```
Will generate invalid python code:
```python
# Top of the file omitted
TestEnum = enum_type_wrapper.EnumTypeWrapper(_TESTENUM)
None = 0
Something = 1
for = 2
class = 3
```

This merge requests proposes change to generator so it will append underscore `_` character to reserved Python keywords as stated in [PEP8](https://www.python.org/dev/peps/pep-0008/)

> If a function argument's name clashes with a reserved keyword, it is generally better to append a single trailing underscore rather than use an abbreviation or spelling corruption. Thus class_ is better than clss. (Perhaps better is to avoid such clashes by using a synonym.)

Generating following code from proto file:
```python
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tests.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btests.proto*7\n\x08TestEnum\x12\x08\n\x04None\x10\x00\x12\r\n\tSomething\x10\x01\x12\x07\n\x03\x66or\x10\x02\x12\t\n\x05\x63lass\x10\x03\x62\x06proto3')
)

_TESTENUM = _descriptor.EnumDescriptor(
  name='TestEnum',
  full_name='TestEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Something', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='for', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='class', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=15,
  serialized_end=70,
)
_sym_db.RegisterEnumDescriptor(_TESTENUM)

TestEnum = enum_type_wrapper.EnumTypeWrapper(_TESTENUM)
None_ = 0
Something = 1
for_ = 2
class_ = 3


DESCRIPTOR.enum_types_by_name['TestEnum'] = _TESTENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
```

This Pull Request also fixes #4833

### CODE REVIEW

**Comment by yoks** [comment]
I signed it!

**Comment by anandolee** [comment]
Thanks for the PR. The change and proposal looks good to me, but as it changes generated code and involves naming, it may need to go through google internal API review and need to be well tested that the change does not break internal projects. 

I will raise this proposal up in our internal meetings.

**Comment by anandolee** [comment]
Update: as keyword conflict on fields can work with getattr()/setattr(), append '_' to other descriptors may confuse users. Another proposal that make getattr() work with message, top level enum, top level enum value, top level extension is under review

**Comment by anandolee** [comment]
The change is submitted in internal. Expect to see the fix in 3.8.0 release.

**Comment by anandolee** [comment]
Closing it as the keyword support is already in master and we will release 3.8.0 soon

**Pull request closed without merging**
