### PR TITLE
Fix 9825, Java's memoized hash code can fail to be memoized.

### PR DESCRIPTION
**Pull request by shawjef3**
Fixes https://github.com/protocolbuffers/protobuf/issues/9825.

### CODE REVIEW

**Comment by perezd** [comment]
This I see #9830, #9829 and #9828 are basically identical, can you close all but one?

**Comment by shawjef3** [comment]
If this is accepted as a bug, I'd think all of the branches should be fixed? Or at least certainly protobuf 4.

**Comment by perezd** [comment]
This branch doesn't really exist. So lets close it.

**Comment by shawjef3** [comment]
Yes, although I don't know which to keep. I figure all the different
versions should be fixed.

**Pull request closed without merging**
