### PR TITLE
Fix C# generator handling of a field named "none" in a oneof

### LINKED ISSUE #9605: [C#] oneof cannot have a field named none
**What version of protobuf and what language are you using?**
Version: master (https://github.com/protocolbuffers/protobuf/commit/5ad0697c868235f24559dc07f8a42870d160af76)
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Linux (ArchLinux 5.16.12-arch1-1), x86_64

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc version

**What did you do?**
1. Build `protoc` in a way described [here](https://github.com/protocolbuffers/protobuf/tree/5ad0697c868235f24559dc07f8a42870d160af76/src).
   ```sh
   ./configure
   make -j `nproc`
   ```

1. Define `OneOfTest` and save as `one_of_test.proto`.
   ```proto
   syntax = "proto3";

   message OneOfTest {
     oneof options {
       int32 none = 1;
       string name = 2;
     }
   }
   ```

1. Compile `one_of_test.proto` (this step finishes successfully).
   ```sh
   ./src/protoc one_of_test.proto --csharp_out=.
   ```

**What did you expect to see**
The generated file (`OneOfTest.cs`) can be compiled successfully.

**What did you see instead?**
Fails to compile `OneOfTest.cs` with the following message:

> OneOfTest.cs(117,5): error CS0102: The type 'OneOfTest.OptionsOneofCase' already contains a definition for 'None'

Here is an excerpt of the generated code.
```cs
  private object options_;
  /// <summary>Enum of possible cases for the "options" oneof.</summary>
  public enum OptionsOneofCase {
    None = 0,
    None = 1,
    Name = 2,
  }
```

Currently, it seems that the compiler generates `None = 0` as a default field value.
https://github.com/protocolbuffers/protobuf/blob/5ad0697c868235f24559dc07f8a42870d160af76/src/google/protobuf/compiler/csharp/csharp_message.cc#L238

If `none` is already defined in `.proto`, the above compilation error will occur.

**Anything else we should know about your project / environment**

### PR DESCRIPTION
**Pull request by jskeet**
Fixed #9605.

(Review one commit at a time; the final commit is just generated.)

### CODE REVIEW

**Comment by jskeet** [comment]
Note: the test protos are generated; I can easily regenerate them after rebasing, when this is approved.

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Review by jtattermusch — APPROVED** [review]
LGTM.

**Comment by jskeet** [comment]
I was going to wait until #9686 was in, but I'll do that separately.

**Comment by jskeet** [comment]
Have actually found some more places I wasn't fixing up - will fix those and request a re-review.

**Review by amanda-tarafa — APPROVED** [review]
LGTM still!

**Comment by jskeet** [comment]
Thanks Amanda. Will rebase again, look into the MacOS changes, and then merge if it's green.

**Pull request merged**
