### PR TITLE
fix: convert native PHP floats to single precision

### PR DESCRIPTION
**Pull request by bshaffer**
See https://github.com/protocolbuffers/protobuf/issues/8165

Converts PHP double-precision floats to single-precision for consistency with the protobuf C-extension

### CODE REVIEW

**Comment by haberman** [comment]
This PR looks reasonable to me on first glance, but appears to cause some test failures. @bshaffer want to investigate?

**Comment by bshaffer** [comment]
@haberman I unfortunately can't see the details of the failing tests - getting 404s on both of them when I click "Details". Running the tests locally now to investigate...

**Comment by bshaffer** [comment]
The failing tests are for Ruby, which was not effected by this change, so I think they're just flakey.

**Comment by haberman** [comment]
The Ruby 3.0 tests are brand new, we can disregard them until https://github.com/protocolbuffers/protobuf/pull/8134 is merged.

**Comment by Eubanks688** [comment]
#8343

**Comment by Eubanks688** [comment]
#7854

**Pull request merged**
