### PR TITLE
Down integrate Google3 changes to Github

### PR DESCRIPTION
**Pull request by rafi-kamal**

### CODE REVIEW

**Comment by rafi-kamal** [comment]
Fixes https://github.com/protocolbuffers/protobuf/issues/6718

**Comment by rafi-kamal** [comment]
@TeBoring can you please look at the conformance test failures?
Also @TeBoring @anandolee looks like the Java tests are failing with the following error:
```
[ERROR]   The project com.google.protobuf:protobuf-java-util:3.11.0-rc-0 (/tmp/protobuf/protobuf/java/util/pom.xml) has 2 errors
[ERROR]     Non-resolvable import POM: Could not find artifact com.google.protobuf:protobuf-bom:pom:3.11.0-rc-0 in central (https://repo.maven.apache.org/maven2) @ com.google.protobuf:protobuf-parent:3.11.0-rc-0, /tmp/protobuf/protobuf/java/pom.xml, line 68, column 19 -> [Help 2]
```

Let's discuss this with Tomo.

**Comment by TeBoring** [comment]
@suztomo seems the pom issue happens again. Could you help take a look?

**Comment by suztomo** [comment]
I’m OOO until Oct 17th. I will check the detail after that. I see Linkage Monitor presubmit succeeded:

379A855C-01D7-408C-B80C-59DCC0D3BA2C

**Comment by rafi-kamal** [comment]
https://github.com/protocolbuffers/protobuf/pull/6786 should fix the javalite build failure.

**Pull request merged**
