### PR TITLE
[PHP] Updated upb to pick up several bugfixes.

### PR DESCRIPTION
**Pull request by haberman**
This fixes most of PHP's remaining conformance failures.

### CODE REVIEW

**Comment by haberman** [comment]
Fixes: https://github.com/protocolbuffers/protobuf/issues/7732

**Comment by haberman** [comment]
There is a goldenfile test failure.

I am guessing this is because upb now properly respects the proto3 semantics of packed serialization by default.

**Comment by TeBoring** [comment]
https://github.com/protocolbuffers/protobuf/pull/7588/files
I updated the golden file in this PR. Feel free to copy any change you need.

**Comment by haberman** [comment]
Hmm, I updated the golden file test, but the golden file compatibility test is broken. The old test expects that the field is encoded as not packed.

@TeBoring could you figure out a solution for this? It seems we will need to change or patch the compatibility tests.

**Comment by TeBoring** [comment]
Continued in #7740

**Pull request closed without merging**
