### PR TITLE
Updated cmake path to io_win32.h

### LINKED ISSUE #6382: io_win32.h referred in extract_includes.bat.in is missing
**What version of protobuf and what language are you using?**
Version: master

**What operating system (Linux, Windows, ...) and version?**
Windows 10 Home

**What did you do?**
```
c:\build\adambadura-protobuf\MSVC>cmake -G "Visual Studio 16 2019" -Dprotobuf_BUILD_TESTS=ON -Dprotobuf_BUILD_CONFORMANCE=OFF -Dprotobuf_BUILD_EXAMPLES=ON "C:\Users\Adam Badura\Dropbox\Projekty\adambadura-protobuf\cmake"
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
-- The C compiler identification is MSVC 19.21.27702.2
-- The CXX compiler identification is MSVC 19.21.27702.2
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.21.27702/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.21.27702/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.21.27702/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.21.27702/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 1
-- 3.9.0.1
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
CMake Warning (dev) at install.cmake:60 (message):
  The file "C:/Users/Adam
  Badura/Dropbox/Projekty/adambadura-protobuf/src/google/protobuf/stubs/io_win32.h"
  is listed in "C:/Users/Adam
  Badura/Dropbox/Projekty/adambadura-protobuf/cmake/cmake/extract_includes.bat.in"
  but there not exists.  The file will not be installed.
Call Stack (most recent call first):
  CMakeLists.txt:250 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: C:/build/adambadura-protobuf/MSVC
```

The file `io_win32.h` indeed does not exist under `src/google/protobuf/stubs`.

### PR DESCRIPTION
**Pull request by acozzette**
Fixes #6382.

### CODE REVIEW

**Comment by TeBoring** [comment]
Do we have any cmake test?

**Comment by acozzette** [comment]
No, I don't think we have any CMake tests yet.

**Comment by TeBoring** [comment]
Can we set up one for cmake on windows?

**Comment by acozzette** [comment]
That test would be nice to have, though I'm not sure if I have cycles to work on it now.

**Pull request merged**
