### PR TITLE
#9293 - incompatible return type php 8.1

### PR DESCRIPTION
**Pull request by oleg1540**
Fix missing function's return type declaration (incompatible return type php 8.1)

### CODE REVIEW

**Comment by oleg1540** [comment]
@elharo hi, re-run checks, please

**Comment by caugner** [comment]
Fixes #9293.

**Comment by oleg1540** [comment]
Added return types compatible with php 7 for all methods. For return types `void` and `mixed` added `#[\ReturnTypeWillChange]` and `TODO`.

@acozzette  Now the tests should pass successfully )

**Comment by haberman** [comment]
I think this is obsoleted by https://github.com/protocolbuffers/protobuf/pull/9370?

**Comment by oleg1540** [comment]
> I think this is obsoleted by #9370?

Yes, 9370 resolve the same problem. Diff with 9370 - some todo's related to updating php version.

**Pull request merged**
