### PR TITLE
adding protoc support for s390x

### PR DESCRIPTION
**Pull request by salamaniibm**
PR for #6486

### CODE REVIEW

**Comment by salamaniibm** [comment]
@googlebot I signed it!

**Comment by acozzette** [comment]
@salamaniibm It looks like something is wrong with the CLA. It might be because the email address on the commit isn't recognized--could you try updating the commit so that it shows your main work email address?

**Comment by salamaniibm** [comment]
@googlebot I signed it!

**Comment by salamaniibm** [comment]
@acozzette thanks for pointing it out. I changed commit author with main email now.

**Comment by acozzette** [comment]
@salamaniibm Looks great, could you just update protoc-artifacts/README.md to mention the new protoc artifact?

**Comment by salamaniibm** [comment]
@acozzette Updated the PR to mention the new protoc artifact

**Pull request merged**
