### PR TITLE
Update Google.Protobuf.Tools.nuspec

### PR DESCRIPTION
**Pull request by deannagarcia**
Find all source files inside the csharp directory. We have to prepopulate this directory anyway, so we can put the .proto files directly into the csharp directory.

The current setup can find the files in linux, but for some reason it isn't copying them correctly unless the files are in the csharp folder

### CODE REVIEW

**Comment by jskeet** [comment]
> We have to prepopulate this directory anyway

Is that in some other bit of the release script? I'm not aware of it at the moment.

**Comment by deannagarcia** [comment]
> > We have to prepopulate this directory anyway
> 
> Is that in some other bit of the release script? I'm not aware of it at the moment.

Yep, this is part of our internal release process and is the migration of [this file](https://github.com/protocolbuffers/protobuf/blob/main/kokoro/release/collect_all_artifacts.sh).

**Review by jskeet — APPROVED** [review]
Okay - if you're happy this is right, then I'm fine with the change.

**Comment by zhangskz** [comment]
I believe this was submitted already in https://github.com/protocolbuffers/protobuf/commit/196193d65cb111913f1615853b44ff60aa8a533d but not auto-closed since it wasn't imported via copybara.

**Pull request closed without merging**
