### PR TITLE
Import MutableSequence from collections.abc on Python 3.

### PR DESCRIPTION
**Pull request by benjaminp**
Fixes https://github.com/protocolbuffers/protobuf/issues/5335.
Fixes https://github.com/protocolbuffers/protobuf/issues/5865.

### CODE REVIEW

**Comment by hugovk** [comment]
I think this should also fix https://github.com/protocolbuffers/protobuf/issues/5865#issuecomment-503434078.

**Comment by tseaver** [comment]
The patch looks fine to me.  Is there a blocker on merging it?  The Python 3.8.0 release is expected 2019-10-21.

**Comment by hugovk** [comment]
Agreed. It is important to release this soon, Python 3.8 is already in feature-freeze beta for final testing by third-party projects before release.

https://www.python.org/dev/peps/pep-0569/#schedule

Thank you!

**Comment by yuvadm** [comment]
Python 3.8 is already out, any reason this fix isn't being merged?

**Comment by knedlsepp** [comment]
@gerben-s @dankurka @jtattermusch Could someone review this?

**Comment by lidizheng** [comment]
@anandolee PTAL

**Pull request merged**
