### PR TITLE
Fix issue with version.rc

### PR DESCRIPTION
**Pull request by shardator**
Based on commit for issue #5448:
```
commit 291d9a0ab0b452537d22a81b551eaea53fd157a8
Author: Ivan Shynkarenka <chronoxor@gmail.com>
Date:   Tue May 15 23:19:58 2018 +0300

    Fix issue with version.rc
```

### CODE REVIEW

**Comment by shardator** [comment]
Any chance that this can be accepted?

**Comment by zchrissirhcz** [comment]
@acozzette Hi, I think there are still some people using protobuf 3.6 branch, and accept this PR to 3.6.x branch should be OK.

**Comment by zchrissirhcz** [comment]
Actually, @shardator 's PR only change one thing: only if on MSVC platform, assign value to `protoc_rc_files` variable in `cmake/protoc.cmake`. This only-two-line fixing, however, takes me many minutes to figure it out. In my opinion, branch 3.6.x should at least be OK to be build.

**Comment by shardator** [comment]
@acozzette I agree with @zchrissirhcz that even though 3.6.x will be "archived" it should be possible to build it on all platforms, that's why this patch is necessary. Since this change is non-functional, I think it is safe to accept it. Also if 3.6.x will be abandoned it cannot really cause too much harm.

**Pull request closed without merging**
